### PR TITLE
Finished ItineraryController unit tests

### LINKED ISSUE #895: Finish unit test for ItineraryController
finish unit tests for #878 (stubs provided). Unit tests live in ItineraryAdminControllerTests. Please reach out to me with any questions

### PR DESCRIPTION
**Pull request by cj-taylor**
Closes #895

### CODE REVIEW

**Comment by cj-taylor** [comment]
My first contribution to the cause. I warmly welcome any and all feedback. Also, the incremental commits are likely spurious to the larger git-history; more than happy to squash them. However, I believe that's now a feature within Github UI when merging (what I was banking on at least :smile:).

**Comment by tonysurma** [comment]
Thank you @cj-taylor!

We can definitely squash as we merge so no problems there.

@mgmccarthy or @MisterJames if you can take a review peek that would be great.  Thanks all

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames @cj-taylor, I'll try to get to a code review today. I'm trying to wrap up #955 right now, so I want to get a PR in for that first.

**Comment by MisterJames** [comment]
@cj-taylor dood you steam-rolled #895. Nice work. :)

:shipit:

**Pull request merged**
