### PR TITLE
Rename to AllReady

### LINKED ISSUE #1: Replace PrepOps with allReady
During initial dev 'PrepOps' was a codename and it has gotten into just about everywhere from folder names to namespaces to variables etc.  This will touch just about everything but we need to move over to 'allReady' going forward.

### PR DESCRIPTION
**Pull request by MattGal**
This set of commits fixes #1 .  I split it into more than one commit so that folks could review the Cordova app changes separately, as I had worked on the other projects.

### CODE REVIEW

**Comment by tonysurma** [comment]
Thanks Matt!  I am working on verifying the current code with tests and update to cordova.  Whatever changes, if any I need to make for that I will push up and then we can work to merge in your changes on top of that or vice versa.

**Comment by MattGal** [comment]
@tonysurma ,
Renaming everything makes for a big list of changes, which could be really tough to rebase on someone else's changes.  Sounds like it's going to be a challenging merge either way, let me know which way you go and I'll try to help out.

**Comment by tonysurma** [comment]
verified all works and other changes can be done on top of this so merging/accepting - thanks again Matt.

**Comment by tonysurma** [comment]
Just a note for (at least my) future reference, I followed this with a commit to update .gitignore for legacy prepopsapp files and to remove some renamed items that wound up in the commits in the mobile app even though they are 'now' in the .gitignore with the new name

**Pull request merged**
