### PR TITLE
Add TimeZoneID to Event

### PR DESCRIPTION
**Pull request by dpaquette**
Adding TimeZoneID to Event class and cleaning up `DateTimeOffset` adjustment code.
- [x] Add TimeZoneID to Event class
- [x] Default Event's TimeZoneID to the TimeZoneID from the Campaign
- [x] Update Event and Task Edit actions to use the event's TimeZoneID instead of Campaign's TimeZoneID
- [x] Automatically adjust DateTimeOffset values based on TimeZoneID
- [ ] Unit tests
- [ ] Documentation on usage

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@dpaquette, I just had  a chance to step through this code, and ModelBinding is pretty powerful! Are we waiting to merge this for any reason? If not, I'd say merge it now, and we can get going on other PR's that are waiting on this code.

**Comment by dpaquette** [comment]
I haven’t added unit tests yet but I do think it is in OK shape to merge otherwise. I have some more cleanup to do and some documentation to add but we could merge if it will help you.

**Comment by mgmccarthy** [comment]
@dpaquette the unit tests can be broken out into Issues and labeled as jump-ins for the repo...

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames can this be merged please?

**Comment by tonysurma** [comment]
@mgmccarthy @dpaquette There is a merge conflict but then I will/can merge.  can either of you create an issue or two to track the open items?

**Comment by dpaquette** [comment]
I will add a couple other issues related to date times

**Comment by tonysurma** [comment]
Merged Live during our Standup!

**Pull request merged**
