### PR TITLE
Beta 8 Upgrade

### PR DESCRIPTION
**Pull request by dpaquette**
Upgraded to the latest beta of aspnet5. Don't forget to upgrade your local environment (`dnvm upgrade`) and install the latest VS tooling (http://www.microsoft.com/en-us/download/details.aspx?id=49442)

### CODE REVIEW

**Comment by dpaquette** [comment]
Resolves issue #88

**Comment by dpaquette** [comment]
I can take a look at these merge conflicts tonight

**Comment by dpaquette** [comment]
Merge conflicts have been resolved

**Comment by MisterJames** [comment]
Looks good from my end @dpaquette.

:shipit:

**Pull request merged**
