### PR TITLE
Removing EventSignups

### LINKED ISSUE #1213: Remove EventSignups Table
Further to issue #919 and PR #1208 we believe we can and should remove the EventSignups table.

There is no longer the concept of a direct event volunteer signup. All signups occur against tasks. Therefore, maintaining this table is extra work and risks becoming out of sync with the true signups. By removing this table we can instead enumerate the signups where required by reviewing signups for all associated tasks.

This was kept as a separate block of work since it directly affects areas such as notifications and a few other key areas of the application that refer to this table.

### PR DESCRIPTION
**Pull request by stevejgordon**
Fixes #1213 

This is a fairly large PR as the removal of the EventSignup table had numerous knock on effects. A majority of it is removal of code and actions that supported the concept of a volunteer signup to an event. This is no longer available and all signups must occur on tasks. I have smoke tested the application in what I believe are the effected areas and functionality seems intact.

We have lost the concept of "All volunteers" tab on the Task Details page (admin) since that was building a list of volunteers assigned to the event, but not the task. Since we don't support event signups this is therefore redundant.

This PR includes a migration which will delete the EventSignup table and modify any relationships.

Many tests were removed that tested functionality that is now gone. Some other tests had to be modified to support the remove of event signups in their test data.

Some javascript was removed also which was specific to event signups.

I hope I have got everything and not broken anything.

I have spotted an odd issue with the notifications being triggered twice but believe this is not due to this change. I will review it further and open an issue to track it.

cc/ @mgmccarthy

### CODE REVIEW

**Comment by tonysurma** [comment]
@MisterJames can we get a second set of eyes on this before we merge?  The changes seem to flow from my quick review

**Comment by tonysurma** [comment]
@stevejgordon sorry but it seems the PR merges have selected you again for a rebase 😸 Thanks in advance

**Comment by mgmccarthy** [comment]
@stevejgordon, let me know what the setup/circumstances are for the notifications being triggered twice and I can look into it. There have been a LOT of changes lately, so I'm sure some things are acting wonky.

**Comment by stevejgordon** [comment]
@tonysurma I must make more sacrifices to the merge gods in future. I'll try to get this done during the day. I might be a bit painful due to a lot of areas being touched in this one.

**Comment by stevejgordon** [comment]
@mgmccarthy Updated the issue #1216 with details to reproduce.

**Comment by stevejgordon** [comment]
@tonysurma - Rebasing proved a bit painful in places but I think I've finished bending the code to my will! This should be good to go after a once over from @MisterJames

**Comment by MisterJames** [comment]
I'm pulling down this PR to run the app through some manual paces (for UI testing) as well.

**Comment by mgmccarthy** [comment]
NICE, it's merged! Sorry I couldn't help. When I have a running machine again, I'll dive back in.

**Pull request merged**
