### PR TITLE
Adding some tests

### LINKED ISSUE #1773: Add tests for OptimizeRouteCriteria
I've started this to validate the behaviour

### PR DESCRIPTION
**Pull request by stevejgordon**
Fixes #1773 

A few tests for this simple criteria class

### CODE REVIEW

**Comment by chinwobble** [comment]
@stevejgordon I was wondering why OptimizeRouteCriteria.cs was edited.
You have made the setters public but shouldn't these properties only be allowed to be set in the constructor?

**Comment by stevejgordon** [comment]
@chinwobble Good catch - thanks!! I meant to remove the setter entirely.

**Comment by chinwobble** [comment]
@stevejgordon hopefully because this PR makes the exact same change as PR #1705 there won't be any merge conflicts.

**Comment by stevejgordon** [comment]
@chinwobble Hopefully it'll merge but I can take the rebase if we need to. @tonysurma please merge #1705 first and I'll do the necessary to adjust this one after if it's conflicting.

**Pull request merged**
