### PR TITLE
Add external link to campaign details

### LINKED ISSUE #692: 6.1.1.4	Add external link and highlight it on campaign display page
Update campaign display page to display and highlight an external link for the campaign to link to an outside page that displays information about the campaign and/or allows folks to request the services of the campaign.  Also verify that the image/logo and rich content description is displayed as well.

### PR DESCRIPTION
**Pull request by dpaquette**
Closes #692

### CODE REVIEW

**Comment by dpaquette** [comment]
image

**Comment by bsomz100** [comment]
+            ExternalUrl = campaign.ExternalUrl;
 +            ExternalUrlText = campaign.ExternalUrlText; 

????

**Comment by tonysurma** [comment]
Looks good to me, @MisterJames or @mheggeseth can we get a second set of eyes before we accept

**Comment by dpaquette** [comment]
Looks like both this PR and #714 have migrations. One of these (whichever is merged last) will need to rebase and recreate the migration to ensure the model is in sync.

**Comment by tonysurma** [comment]
@dpaquette I just merged the other so you have been chosen to have the honor of the rebase and recreate migration - thanks in advance for doing that 😄

**Comment by dpaquette** [comment]
Yay! I win! I will do that later tonight

**Pull request merged**
