### PR TITLE
#2031 - Significant Upgrade to Cordova Mobile Project

### PR DESCRIPTION
**Pull request by SteveKennedy**
This Pull Request addresses Issue #2031 

Watch: https://www.youtube.com/watch?v=qSrkqmxI3_s

Includes upgrade to latest version of Ionic and webpack build, Angular 4 and component based pattern, removes bower dependency, UI update with Login, Hours, Events, and Logout. Removed ESlint, since latest Ionic and Angular are Typescript. Enhanced Readme with installation and configuration details. The only files effected should be in the  AllReadyApp/Mobile-App project only.  No files outside of the Mobile-App project should have been touched in this Pull Request.

### CODE REVIEW

**Comment by SteveKennedy** [comment]
@digitaldrummerj I would appreciate your thoughts on this upgrade.

**Comment by MisterJames** [comment]
@SteveKennedy would you recommend moving to VS Code as the tool chain for the mobile app?

**Comment by SteveKennedy** [comment]
@MisterJames Either that or go to Xamarin.  But yeah, it's easier to do Ionic dev in VSCode, and use the Ionic CLI.  But that's not a familiar experience for traditional VS devs...

**Comment by MisterJames** [comment]
Great value in this PR and your comments, @SteveKennedy. Thanks for this.

I would support a VS Code approach for the mobile project, deprecating the VS 2017 requirement. I would rather have an eco system that was supported and known by the community who knows the toolkit best.  @tonysurma any thoughts here?  Any objections to a VS Code approach for mobile?

**Pull request merged**
