### PR TITLE
Solution to Issue #1411

### PR DESCRIPTION
**Pull request by dcbrewster**
Fixes Issue #1411

### CODE REVIEW

**Comment by tonysurma** [comment]
thanks @dcbrewster 
@stevejgordon can you take a look? thanks

**Comment by stevejgordon** [comment]
@tonysurma - Sure, might not be today but will try to review over the weekend

**Comment by naeemsarfraz** [comment]
I'm looking into this issue and just submitted a WIP PR #1723, I've kept @dcbrewster's commit and added to it. However the PR is not yet finished.

**Comment by BillWagner** [comment]
These commits were merged as part of #1685 

Closing this.

**Pull request closed without merging**
