### PR TITLE
Fixed requests filter bug 

### LINKED ISSUE #2020: Itinerary Details - Filtering
When I filter the linked requests on the itinerary details page if no results are included in the filter I loose the ability to remove or adjust the filter.

Expected Result: When I apply a filter within the Itinerary Details (admin) page (request section), it should return any requests matching that filter. When no requests match, it should allow me to remove the filter or change the filter values.

Actual: The filter and the requests table are removed from the page and I am unable to adjust / remove the filter. There is no indication that a filter is applied. The only way to recover is to use the browser back button. Refreshing is not an option as it re-applies the form submission.

This needs to be fixed to ensure that an applied filter can be adjusted if it returns zero results.

### PR DESCRIPTION
**Pull request by mk0sojo**
Fixed issue where filter UI disappears when no Requests are present. Also fixed issue with ItineraryId being read from ItineraryRequest table rather than Request table where it is not populated

Closes #2020

### CODE REVIEW

**Comment by MisterJames** [comment]
Thanks @mk0sojo! Looks like there's a build server error, we'll have a look at this over the weekend. Cheers!

**Comment by mk0sojo** [comment]
Thanks @MisterJames . Did you ever figure out what the problem with the build server was?
Looking at the error message it seems to be a problem with bower, but we are not using that anymore (?) so maybe it should work now.

**Comment by MisterJames** [comment]
@mk0sojo Just getting back to this and the extra commits got the build passing. Would you be able to do a rebase here to clean up the commits?

**Comment by mk0sojo** [comment]
@MisterJames Did a rebase. Hopefully that solved it.

**Comment by mk0sojo** [comment]
Looks like something has gone a bit out of sync with this branch. Will have another look later.

**Comment by mk0sojo** [comment]
I've done a rebase with the following commands:
git checkout master
git fetch upstream
git merge upstream/master
git checkout issue-branch-2020
git rebase master

If I run git status after this I get:
On branch issue-branch-2020
Your branch and 'origin/issue-branch-2020' have diverged,
and have 2 and 11 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working tree clean.
I did a "git pull" and then "git push origin issue-branch-2020 -f", but not sure if this solved the problem? Any Git expertise appreciated.

**Comment by jonparker** [comment]
@mk0sojo The rebase you did seems fine to me.

**Comment by MisterJames** [comment]
Thanks @mk0sojo, I rebased locally from master and merged.

I did the following:
```
git checkout -b mk0sojo-issue-branch-2020 master
git pull https://github.com/mk0sojo/allReady.git issue-branch-2020
git rebase master
git co master
git merge --no-ff mk0sojo-issue-branch-2020
git push origin master
```

I have the luxury of working against the HTBox repo directly, so I got to sideswipe some of the indirection from the fork/pull/status you were experiencing. If you're in a troubled state, I would recommend deleting your fork and your local version (and then fork/clone again). It only takes a moment. There is definitely a benefit to working through the merge mayhem, but sometimes it's way over our head and breathing in and out and restarting is the easier path ;)

**Pull request closed without merging**
