### PR TITLE
stubbing out unit tests for ManageController

### LINKED ISSUE #631: stubbing out unit tests for ManageController
Part of work for #620. 

I'm currently working on this one. When I submit a PR for this, project owners can have a look and see if they want tests renamed, re-ordered, etc...

@tonysurma please assign to me

### PR DESCRIPTION
**Pull request by mgmccarthy**
Fixes #631

### CODE REVIEW

**Comment by mgmccarthy** [comment]
so this was the build failure:
image

how do I retry the build?

**Comment by BillWagner** [comment]
Tony or I can restart the build (it requires logging into AppVeyor). If it's actually a problem with your code, pushing a change to your branch will restart the build.

**Comment by mgmccarthy** [comment]
@BillWagner code builds and all unit tests run, but it now looks like the build succeeded, so I'm assuming we're good to go now?

**Comment by BillWagner** [comment]
Merging.

**Pull request merged**
