### PR TITLE
Fixes #1782 zip code to postal code

### LINKED ISSUE #1782: Rename all instances of "Zip" or "ZipCode" to "PostalCode"
A "Zip" or "ZipCode" is very specific to the USA. allReady can be run anywhere. "PostalCode" is a bit more generic on locale than "ZipCode", so I'm thinking it makes more sense internationally.

@stevejgordon this one is for you ;)

### PR DESCRIPTION
**Pull request by shahiddev**
Zip or Zip Code within the context of allReady application has been updated to the more globally recognised term "Postal Code" 
CSV import expected headers have also been updated to expect "postalcode" column.

Considerations:
Changes impact large number of files
Contains a DB migration

Fixes #1782

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@shahiddev, I'll try to get eyes on this in the next couple of days

**Comment by stevejgordon** [comment]
Something to watch out for is that @naeemsarfraz's PR for task renaming also includes a migration. So this one might need a fresh migration to be created once rebased on that to ensure the upgrade flows correctly. Otherwise the snapshots could get out of alignment.

**Comment by mgmccarthy** [comment]
@naeemsarfraz cc @stevejgordon @shahiddev 

we should probably merge the renaming task PR first then, as I'm sure that's a very migration heavy PR.

Is there a pending code review for the PR?

**Comment by naeemsarfraz** [comment]
@mgmccarthy, @stevejgordon did a review yesterday but I've since added a bunch of changes which I have pushed.

I think I'm 90% done. I just need to check that View and ViewModels are all in sync.

**Comment by shahiddev** [comment]
@mgmccarthy I've rebased this PR against master and fixed up a few conflicts, have smoke tested again (no pun intended!) and looks ok.

**Comment by tonysurma** [comment]
other PR merged and this is rebased - thank you!

@mgmccarthy @stevejgordon any review comments or is this good to go?  thanks.

**Comment by mgmccarthy** [comment]
@tonysurma @shahiddev, I'll try to get eyes on this today, but I've been unable to dedicate a lot of time to allReady as my regular job commitments have been overtaking a lot of that spare time. If anyone else wants to jump in on the code review, they're more than welcome

**Comment by mgmccarthy** [comment]
@tonysurma sorry about that. I've hit that "Closed" button more than once by accident.

**Comment by naeemsarfraz** [comment]
I don't mind lending a hand as this is one the first PR's following the large rename I did recently.

I think the rebase might have gone a little funny here as changes from master (my rename PR) appear as changes in this branch which makes it difficult to see what the actual changes are @shahiddev. This is also reflected in the commit history on this PR.

**Comment by tonysurma** [comment]
thanks @naeemsarfraz , @BillWagner @stevejgordon correct me where I go wrong but I believe those changes from another PR are part of the rebase as his changes build on those after rebase...

**Comment by shahiddev** [comment]
@tonysurma That was my understanding too hence why I wasn't concerned about it...

**Comment by naeemsarfraz** [comment]
Something similar happened to me too on my previous PR.

You're right @tonysurma, the changes, or should I say updates from master, have been applied but they shouldn't appear here. This might not be an issue and when merged in it might be ok, just slightly worried that it might mess with the history on master if it's not. Maybe @BillWagner could take a quick look?

I pulled down the PR and had a look at the history, does this look right? Four changes appear twice.
image

I'm a newbie to Github flow so this might just be normal but I do see others have flagged this up before [here](http://stackoverflow.com/questions/18323665/pull-request-on-github-showing-commits-rebased-from-master) and [here](http://stackoverflow.com/questions/40413071/after-rebasing-my-github-fork-commits-from-others-are-in-my-pull-request).

**Comment by stevejgordon** [comment]
I have seen this on some other PRs. I think it happens if the code is merged in, rather than rebased, but I might be wrong. @shahiddev how did you rebase? I wrote about the steps I use in one of my first blogs - https://www.stevejgordon.co.uk/contributing-to-allready

I think merging in might be okay from a code point of view. Agree though, not sure what happens to the history which worries me a little.

**Comment by shahiddev** [comment]
@stevejgordon I definitely rebased, I sync'ed my master branch with upstream (HTBox/Allready), then rebased my branch from master and pushed. 
My github foo isn't as strong as others though so would welcome any pointers (like your blog post).

**Comment by shahiddev** [comment]
@naeemsarfraz do you mind redacting the email addresses from the screenshot - sorry I know it probably sounds ultra paranoid but I tend prefer to err on the side of caution!

**Comment by tonysurma** [comment]
@shahiddev if he can see those emails via the git repository then anyone who clones this can so he can redact but they are already out there for better or worse...  if you have an email in your profile in git then it gets included in each commit in a repo.

I am always worried about the same thing so appreciate the caution but git doesn't hide much in this situation.  I *think* you can not add email in your local git command line profile and it can't include it in future commits then

**Comment by naeemsarfraz** [comment]
@ShahidDev if you're online in an hour or so I can give you a hand, just
getting the kids to bed

**Comment by shahiddev** [comment]
@naeemsarfraz sure I'm around this evening. Thanks!

**Comment by shahiddev** [comment]
Ok I think I've sorted this out, not sure exactly where I went wrong originally but must have fat fingered something. 
Looking at the positive side I've learnt a lot and surely until you've royally screwed up a PR you're not really trying hard enough ;) 
Thank you everyone for your input and patience

**Comment by tonysurma** [comment]
Yes thank you for hanging in there!

**Pull request merged**
