### PR TITLE
Issue 2011 update Prerequisite Install Guide to include VS2017

### PR DESCRIPTION
**Pull request by marigerr**
[Issue 2011](https://github.com/HTBox/allReady/issues/2011)  
PR updates the Web-App portion of the install guide to latest versions of tools and VS2017.

**Question:**
Has the mobile app been migrated to VS2017?    
When trying to open the mobile app with VS2017, I got the message about a one-way upgrade.

I've started to update Mobile app portion of guide, but not included yet in PR.

### CODE REVIEW

**Comment by stevejgordon** [comment]
@marigerr The mobile app hasn't been touched in some time. I didn't migrate it since I wasn't very clear on it's direction. As part of v1.6 milestone which will start to populate soon, the mobile app does need to be re-invigorated so we should get that updated as necessary. I'll open an issue for that.

cc/ @tonysurma re. mobile app.

**Comment by marigerr** [comment]
@stevejgordon  
Thanks!  
I can submit a 2nd PR (or add onto this one) to update the mobile app part as well since it will be migrated.  
However, I'm not familiar with the mobile-app, so have a couple questions.

- In the guide states:   
_"The mobile application uses the Ionic framework version 1"_.  
But later in instructions when installing Ionic with `npm install -g ionic`   , version 3.4.0 will be installed.  Is the latest version of Ionic ok, or should I add instructions on installing version 1?  
- When running `ionic state restore` , how should these 2 questions be answered? Both Yes?  

     _Detected .\gulpfile.js in project directory, but to integrate gulp with the CLI, you'll need to install ionic/cli-plugin-gulp. Install now? (Y/n)_   

     _Looks like this is an Ionic 1 project, would you like to install ionic/cli-plugin-ionic1 and continue? (Y/n)_ 

- VS2017 has tools bundled differently.  When running the Visual Studio Installer, to add the additional mobile tools, what is needed?   Did I miss anthing such as iOS or Windows phone tools or are they included with Cordova?
- [x] Tool for Apache Cordova
- [x] Java SDK 8
- [x] Android SDK setup (API level 19 and 21)
- [x] Android SDK setup (API level 22)
- [x] Android SDK setup (API level 23)
- [x] Apache Ant

**Comment by stevejgordon** [comment]
I'd suggest a second PR since this one is good to go with the bits we need most urgently for new devs.

I'm not familiar with the mobile project to be able to answer those questions. It's taken a bit of backseat in the last 12 months as the functionality for the main site was updated/defined.

I think it's important we get docs updated so people can work on it again for v1.6 but possibly we make docs a P2 for the v1.6 milestone. Also will depend on the issue #2015 being completed as that may reveal some twists and turns that require changes.

**Comment by marigerr** [comment]
okdoke, makes sense to hold off on updating the mobile part of the guide until after the mobile app has been migrated.
I wonder if it might be helpful to add a short note to the guide after the web-only portion, to indicate that the mobile app and documentation is pending update to VS2017.   
This would help avoid confusion if someone tries to follow the whole guide and comes across the mobile portions still referencing VS2015.

**Comment by stevejgordon** [comment]
@marigerr That's a good idea, yes please.

**Pull request merged**
