### PR TITLE
TestHangfireController.cs failing to build in release mode. #1860

### PR DESCRIPTION
**Pull request by c0g1t8**
Fix for #1860.

### CODE REVIEW

**Comment by tonysurma** [comment]
Thanks again @c0g1t8 .  ping @mgmccarthy as it is a small change but in Hangfire

**Comment by mgmccarthy** [comment]
@c0g1t8 cc @tonysurma

A better fix would be to delete this file. We don't need it. I had initially set it up when working with Hangfire and forgot to delete it. It doesn't do anything.

**Comment by tonysurma** [comment]
thanks @mgmccarthy , @c0g1t8 if you would like to delete the file (and your change 😄 ) then we can pull this in and get it compiling in release!

**Comment by tonysurma** [comment]
@c0g1t8 is it just my eyes or does it seem like the 'change' for the file is removing all the lines vs removing the file?  cc @stevejgordon @BillWagner to double check as I may just be going git blind :)

**Comment by stevejgordon** [comment]
@tonysurma I think that's just how the compare view handles the deletions. I pulled the PR locally and indeed the file is gone so this looks ok to me. :shipit:

**Pull request merged**
