### PR TITLE
Campaign Impact model change, viewmodel change, and related database …

### PR DESCRIPTION
**Pull request by joelhulen**

### CODE REVIEW

**Comment by BillWagner** [comment]
@joelhulen It looks like a merge with another PR made this fail the build, can you fix that?

**Comment by joelhulen** [comment]
Fixed build issue. I had forgotten to include a file in my commit.

**Comment by BillWagner** [comment]
@joelhulen Looks like a merge conflict. Can you pull from upstream and fix them?

**Comment by MisterJames** [comment]
It's a party on Channel9!! 

:confetti_ball: :dancers:

**Pull request closed without merging**
