### PR TITLE
RC1 Update

### PR DESCRIPTION
**Pull request by shawnwildermuth**
Currently requires you're building Autofac manually. Will update and finalize PR once Autofac is released.

### CODE REVIEW

**Comment by shawnwildermuth** [comment]
Btw, the Appveyor wil fail until we get the Autofac working. So just leave the PR done until I change the name (but you know that)

**Comment by stimms** [comment]
Can we just check in the binary for now?

**Comment by shawnwildermuth** [comment]
This should be good to go. Autofac is now released

**Comment by BillWagner** [comment]
@shawnwildermuth It looks like the appveyor build is still trying to use Beta 8. Can you update appveyor.yml to point to the RC build?

**Pull request merged**
