### PR TITLE
Issue branch 1348

### LINKED ISSUE #1348: My Tasks will disappear when a character not in the task is searched for
Repro:
1. Dashboard>>Click current event
2. My Task>>Search put in a character that is not in the task
Note: My task div will disappear.

### PR DESCRIPTION
**Pull request by wmay1991**
Removed data-bind from a parent div from My Assigned Tasks

Fixes #1348

### CODE REVIEW

**Comment by tonysurma** [comment]
cc @stevejgordon 

There appears to be changes to the .sln file as part of this which I don't think is needed.  Is there an issue from the move to vs2017 or maybe just something else that came in?

@wmay1991 let us know how we can help to clear that up/out.

**Comment by wmay1991** [comment]
I recently did a fetch from VS2015 and I received MS Build errors. I did some researched and it seemed to be related to VS2015 being incompatible. I downloaded VS2017 and everything worked fine. You may need to indicate in your instructions that VS2017 should be used.

**Comment by tonysurma** [comment]
thanks @wmay1991 we had just moved to VS2017 in the last few days so good point on our docs needing to be updated.  I think we will need to amend this to not include the sln changes

**Comment by wmay1991** [comment]
image

**Comment by wmay1991** [comment]
I reverted my commit and made sure only the event tasks page was added.

**Comment by tonysurma** [comment]
thanks @wmay1991 merging now

**Comment by wmay1991** [comment]
@tonysurma My company is sponsoring a Hackathon second Friday of May. Is there any section/issues in particular that would be good for us to work on?

**Comment by tonysurma** [comment]
thanks for asking @wmay1991 send me an email if you can to firstname dot lastname at htbox.org and I can connect you with folks who have run hackthons for HTBox at their company like @stevejgordon for some best practices and approaches.  I can also pull you into our slack channel if you like.

Again thanks a lot for your contribution and for thinking of pulling together a hackathon for our project!

**Comment by stevejgordon** [comment]
@wmay1991 Happy to help and thanks for getting involved. After my first code-a-thon I put together this blog post on the event - https://www.stevejgordon.co.uk/running-humanitarian-toolbox-code-thon

**Pull request merged**
