### PR TITLE
Fixes #1565

### LINKED ISSUE #1565: Add PendingConfirmation and Confirmed to the list of Request statuses on Event Details page
Currently, the event details page shows these Request statuses:
image

Since RequestApiController and Hangfire jobs and sms confirmation messages have been added to the system, that's introduced to more Request statuses; Confirmed and PendingConfirmation.

Update the Request status "tiles" to show these two additional statuses.

also adding to update the Event's Request view as well to include to additional two tabs:
image

### PR DESCRIPTION
**Pull request by mgmccarthy**
Ignore what's in the commit comments. All unit tests pass and the UI/functionality has been updated

Fixes #1565

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@tonysurma my build failed with no errors? It only says "Log is Empty". There is no console information

image

**Comment by tonysurma** [comment]
appveyor is being funky so will rerun when they seem up to it.

**Comment by tonysurma** [comment]
And it's good!

**Comment by tonysurma** [comment]
I am going to merge this in.  If @stevejgordon or @MisterJames you find anything with a second set of eyes we can address in a later PR.  Thanks @mgmccarthy

**Pull request merged**
