### PR TITLE
Removed and sorted all using statements in the web project. 

### PR DESCRIPTION
**Pull request by YannickMeeus**
The sort order is a bit funky as ReSharper puts system namespaces first, after which it will sort the remaining statements alphabetically.

### CODE REVIEW

**Comment by manojattal** [comment]
I don't see any error in AppVeyor logs.Not sure why build is failed!

**Comment by YannickMeeus** [comment]
@manojattal It seems to be timing out when starting the tests. AppVeyor, I believe, limits build durations to an hour. The actual build and package phases only take about 2.5 minutes, if the logs are correct.

**Comment by mgmccarthy** [comment]
@YannickMeeus, @manojattal. I'm having the same problem with my PR's builds failing (check out #576). Not too sure what's going on right now.

**Comment by tonysurma** [comment]
@YannickMeeus  please rebase off of master as we now have a fix for the build/test issues!

**Comment by YannickMeeus** [comment]
@tonysurma Cool, I'll get that done this evening.

**Comment by YannickMeeus** [comment]
@tonysurma All done.

**Pull request merged**
