### PR TITLE
Finished all tests for AccountController

### LINKED ISSUE #661: write unit tests for AccountController
@tonysurma please label with "jump-in". Part of Issue #620

stubs are provided in:
AccountControllerTests.

### PR DESCRIPTION
**Pull request by ExoltenOne**
* Finished all tests for AccountController. 
* Refactored RedirectAccountControllerRequests to have IUrlHelper injected via constructor.

Closes #661

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@ExoltenOne, this is a YUUUUGGEEE PR... it's going to take me a long time to get through it. 

For future reference, if you plan to submit a PR with these many changes, it's best to label the PR title with the word "WIP" in the front, and then you can make smaller commits and I'll review them as you finish them up....

Thanks

**Comment by ExoltenOne** [comment]
@mgmccarthy, sorry for the inconvenience. Next time I'll split it but believe me I was also suffering - a merge was terrible.

**Comment by mgmccarthy** [comment]
@ExoltenOne, yeah, I'm sure a rebase on all this work had to be hell. Thanks for sticking through it, I'll probably be starting the review soon

**Comment by mgmccarthy** [comment]
@ExoltenOne what was the reasoning behind injecting` IUrlHelper` into `RedirectAccountControllerRequests` when before it was being passed into `RedirectToLocal`?

Were you having a problem writing the unit tests b/c of having to supply that to `RedirectToLocal`?

**Comment by ExoltenOne** [comment]
The reason why I moved an injection from a method to a constructor is simply a purpose of how we should use them. The method injection should be used in a case where dependency is being changed dynamically. Here we have the same UrlHelper all the time. It doesn't change. For each request, UrlHelper stays the same and that's why I decided to change it.

**Comment by mgmccarthy** [comment]
@ExoltenOne, thank you for the GARGANTUAN effort behind finishing up these unit tests. These unit tests represent some of the hardest to test in the system and stepped up and implemented them. 

Thanks so much for you contribution.

@tonysurma @MisterJames :shipit:

**Comment by ExoltenOne** [comment]
@mgmccarthy thanks for your words and see you in other tasks 😄

**Pull request merged**
