### PR TITLE
#1873 home page - separate tabs for login and register.

### PR DESCRIPTION
**Pull request by babagy**
This is a request that simply demands separate tabs for login and register on the home page.

### CODE REVIEW

**Comment by babagy** [comment]
Should I did do it again and send a pull request?

**Comment by stevejgordon** [comment]
@babagy There are a couple of I think unrelated commits in here. If you're able to back those out and recommit the work you did, you can force push the branch to update this PR. If you think it's easier to close the PR though we can start from a fresh one. Let me know if you need a hand at all and thanks for your patience on the Git side of things.

**Comment by babagy** [comment]
Please Steve, close the PR an I wish pull the current version and work
afresh then submit a new PR.

**Comment by stevejgordon** [comment]
Ok, thanks @babagy

**Pull request closed without merging**
