### PR TITLE
WIP: Campaign tags issue #247

### PR DESCRIPTION
**Pull request by naeemsarfraz**
See #247 for description

### CODE REVIEW

**Comment by stevejgordon** [comment]
@naeemsarfraz Still WIP?

**Comment by naeemsarfraz** [comment]
Oh yeah for sure @stevejgordon. The change I made was just to hard code tags in so that I can demo what the change would look like.

I was looking for feedback as per my last set of [comments](https://github.com/HTBox/allReady/issues/247#issuecomment-279110687). In any case I will crack on with this later in the week.

**Comment by MisterJames** [comment]
@naeemsarfraz I've resolved the conflicts in this branch. I know it's been some time, but I'd like to get this wrapped up if we can. How are you feeling about this branch at this point?

**Comment by naeemsarfraz** [comment]
Much appreciated @MisterJames 

I am close to finishing the work but won't be able to able to put any time towards it for another couple of weeks.

**Pull request closed without merging**
