### PR TITLE
Assign task command handler tests

### LINKED ISSUE #868: write unit tests for AssignTaskCommandHandlerAsync
@tonysurma please label with "jump-in". Part of Issue #620

### PR DESCRIPTION
**Pull request by sanilpaul**
Fixes #868

### CODE REVIEW

**Comment by tonysurma** [comment]
@sanilpaul  thank you for the contribution to HTBox!  @mgmccarthy can you take a peek at these and provide any review guidance so we can merge it.

**Comment by tonysurma** [comment]
@sanilpaul I also just invited you to the repo so I can assign the issue and such to you.  Thanks again

**Comment by mgmccarthy** [comment]
@tonysurma, I'll have a look at this tomorrow.

**Comment by sanilpaul** [comment]
@tonysurma Thanks for the invitation. Looking forward to it.

**Pull request merged**
