### PR TITLE
Controllers cleanup

### PR DESCRIPTION
**Pull request by SeanFeldman**
Removed
* Sequential checks
* Unused variables
* Typos
* Unused methods
* Unused controller

### CODE REVIEW

**Comment by mikesigs** [comment]
I'll throw my hat in the ring here. I'm on the side of using var, but I would prefix the variable with "is" to make the code more explicit, e.g. `isValidPostalCode`

**Comment by SeanFeldman** [comment]
@stevejgordon I've reverted that `var`.

**Comment by stevejgordon** [comment]
@mikesigs I agree, I think using the isValidPostCode is a better name and also does help imply what we can expect the result to mean.

**Comment by tonysurma** [comment]
@SeanFeldman  please rebase off of master as we now have a fix for the build/test issues!

**Comment by SeanFeldman** [comment]
@tonysurma rebased.

**Comment by tonysurma** [comment]
@mheggeseth @dpaquette @MisterJames can you take a peek?

**Comment by MisterJames** [comment]
@SeanFeldman my bad, I merged out-of-order. Would you mind doing one more rebase? I'll get it merged ASAP.

**Comment by SeanFeldman** [comment]
@MisterJames done

**Comment by MisterJames** [comment]
Thanks @SeanFeldman!

**Pull request merged**
