### PR TITLE
Split User "name" property

### LINKED ISSUE #846: Split User "name" property
We currently have a name property on the user. This should be broken up into Forename and Surname and any uses of name updated.

Any forms where the user can add their name will need to be adjusted also.

### PR DESCRIPTION
**Pull request by mgmccarthy**
Fixes #846

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@stevejgordon, I'm realizing now that I could have updated my newly created migration instead of creating three separate migrations as part of this refactoring (doh)... I'm still pretty new to EF migrations.

If there is a way for me to clean that up, I will. If not, I know for next time.

**Comment by stevejgordon** [comment]
@mgmccarthy You can unwind a migration or migrations and then create a single new one for all changes. What you need to do is:

1. run a database update specifying a migration name of the migration prior to your changes. So in your case I think it would be dnx ef update database "RequestToEventMapping". This unwinds the changes on your database.
2. next you need to remove (once for each migration) the migrations you've added using dnx ef migrations remove. This updates your snapshot and deletes the migration. Your models remain unchanged though. After doing this three times you should have no migrations of your own.
3. You can then create a new migration which will compare your model to the snapshot and build a single migration to make all relevant changes.

That should work ok. Any questions, let me know.

It's nearly lunchtime for me and I was going to try and pull in your code to my local repo and do my first code review on it. I can wait though until you have any final tweaks added.

It's up to you but since they'll end up with a few commits, some of which override work done in the prior commit I usually soft reset my branch to before I started working and then create a new single commit that includes the final view. It's not totally necessary (and be careful if you do it, not hard reset as you'll loose work!) but I do prefer it since you have one commit showing all changes and it's easier for code review. Sometimes I split the functionality commit work and the testing work into it's own commit since that can make it really clear what actual functional files need checking.

**Comment by stevejgordon** [comment]
@mgmccarthy I've managed to pull those down during lunch. I've not looked over in detail but initially all looks good. You have a todo in the ApplicationUser class asking if firstname and lastname should be required.

I think it's valid that at database level they are not required since we don't always have that data when creating the user from social login so we do need a record to be creatable without them. In the UI wherever we collect the data though I think required is correct based on feedback I had in #840

A think a result of #840 once my further points are answered we should be presenting these fields on the confirmation after social login and enforcing their completion.

I'll try and review more of this a little later.

**Comment by tonysurma** [comment]
I commented on #840 thanks

**Comment by mgmccarthy** [comment]
@tonysurma, my latest commit against this PR has been "building" now in AppVeyor for over a half hour... is it stuck?

**Comment by tonysurma** [comment]
it has been restarted

**Comment by mgmccarthy** [comment]
@stevejgordon when you get a chance, let me know if this looks good. Thanks for the help with the EF7 migration stuff.

**Comment by stevejgordon** [comment]
Look good to me. Thanks Mike. 

If I were being picky you might want to change NotifyAdminForTaskSignupStatusChange and use your computed property Name instead of the FirstName and LastName parts in line 50?

Otherwise I think we can ship it

**Comment by tonysurma** [comment]
Going to ship it and @mgmccarthy can add to it later.  Thanks for the contribution

**Comment by mgmccarthy** [comment]
@stevejgordon @tonysurma I'll take care of that tonight when I get home.

**Pull request merged**
