### PR TITLE
Refactoring IAllReadyDataAccess to mediator in SiteAdminController

### LINKED ISSUE #673: Refactoring IAllReadyDataAccess to mediator in SiteAdminController
Part of #567. I am currently working on this.

### PR DESCRIPTION
**Pull request by mgmccarthy**
Fixes #673

### CODE REVIEW

**Comment by tonysurma** [comment]
@mgmccarthy is this good to go from your side?  @MisterJames review please?

**Comment by mgmccarthy** [comment]
@tonysurma this PR is good to go. Slowly but surely we're moving these controllers to use mediator.

**Comment by MisterJames** [comment]
Thanks again @mgmccarthy...this one has a few more moving parts, so I want to just pull it down and run through it locally...likely Sat AM at this point.

**Comment by MisterJames** [comment]
@mgmccarthy Thanks for this PR!

:shipit: 

One thing that would help on my end is to keep the PRs a little smaller...for example here there were a bunch of tests that could have been updated in a separate pull, the odd clean up on some fake services, etc.   

I really want to support you in this how I can, but my time is a little constrained, so smaller PRs would certainly help. If that's not in your workflow, no problem, but I'll likely only get to them on Saturday mornings (when I have 3-4 hours blocked off for AllReady).

Again, super appreciative of the work you're doing...you're doing the heavy lifting lately, and not the pretty kind. Hope this isn't too much of an ask!

Cheers!

**Comment by mgmccarthy** [comment]
@MisterJames, I assumed that a PR should be all the code ready to go (even if it meant in the big). If I see a PR I'm working on getting too large, I'll submit multiple PR's against one Issue, then let you know then the final PR is in. 

Hopefully, that can scope the work a little better. 

Thanks for letting me know. We're all volunteering time, so I want to make it as easy as I can on project owners.

**Pull request merged**
