### PR TITLE
WIP #36 skill associations

### PR DESCRIPTION
**Pull request by mheggeseth**
Could use a sanity check before proceeding with current plan for #36. See my most recent comment on the issue for a brief summary. I'll need to re-base pending the merge of Shawn's PR #97 refactoring the EF models, but I didn't really know what I was doing in EF anyway so that will be helpful.

### CODE REVIEW

**Comment by dpaquette** [comment]
Maybe @tonysurma can chime in on the requirements perspective.

From a code perspective this looks ok to me. Don't forget to add a database migration for the changes to the model.

**Comment by tonysurma** [comment]
@dpaquette did a quick requirements glance at what @mheggeseth wrote on the other issue and looks good to me

**Comment by mheggeseth** [comment]
@dpaquette Thanks. How do I add a migration?

**Comment by dpaquette** [comment]
It is command line based. Type the following from the AllReadyApp/Web-App/AllReady folder. It should give you an example.

    dnx ef migrations add --help

Note that you will need to change your config.json to use a SQL database instead of InMemory.

**Pull request merged**
