### PR TITLE
Add precise Lat/Lon selection to Request Add/Edit

### PR DESCRIPTION
**Pull request by dchristensen**
This PR takes care of the Request Add/Edit screen for #1501.  If everything looks OK I can continue with the Itinerary screen either as part of this PR or in a separate one.

### CODE REVIEW

**Comment by dchristensen** [comment]
@stevejgordon can you take a look at this

**Comment by stevejgordon** [comment]
@dchristensen Sure - I'll try to take a look later today

**Comment by stevejgordon** [comment]
@dchristensen - Thanks for working on this. I've pulled it an had a look through. I'm a little unsure of the logic around the edit request. At the moment, if the request has Lat/Long and then the address is changed, the lat/long are not updated (no geocoding happens).

This makes sense in some scenarios but I can foresee occasional requirements to completely change an address. In the case of changing (rather than tweaking) an address we might want to geocoding to occur.

This is a little tricky to determine so we might need to consider something in the UI to determine if lat/long should be updated or not. We need to figure that out I think.

I also noticed that you had some js for the mapping. Some of that looks to repeat code we have in site.js. It would be nice to try and reuse/update site.js code so that any mapping code is centralised. Could you take a look at if that could work here? Obviously we need to be vary of breaking the pages using site.js currently!

**Comment by dchristensen** [comment]
@stevejgordon Thanks for looking at this.  I agree this is tricky trying to figure out how to handle these changes.  

Currently, when any of the address fields change I do a geocode lookup on client side:

````javascript
      $("#Address, #City, #State, #Zip").on("change", function () {
            var address = getAddress();
            if (!isAddressEmpty(address)) {
                lookupAddress(address);
            }
        });

   function lookupAddress(address) {
        getGeoCoordinates(address.address1, address.address2, address.city, address.state, address
            .postalCode, address.country, function(l) {
                var location = setLocation(l.latitude, l.longitude);
                if (location !== null) {
                    setMapCenterAndZoom(map, [location], 15);
                }
            });
    }
````
This should update the Latitude & Longitude fields any time the address is changed, but there are no guarantees that request succeeds.  I could add code to the change handler function to set the Latitude & Longitude fields to zero before issuing the request to lookup the address, that way if the geocode fails the request will be geocoded by the back end.

As far as the mapping code, was there any specific code you saw? I have been trying to use what's in site.js when it makes sense (creating the map, center and zoom, geocoding).  Most of the mapping code is to handle manipulating the pushpin.  I could possible try to make it so it could be shared in site.js, but I don't think there is anything in there currently that would provide the control need to handle the movements.

**Comment by tonysurma** [comment]
@stevejgordon any more thoughts on this PR?

**Comment by stevejgordon** [comment]
@dchristensen @tonysurma - I'm not great with JS so will defer to anyone who is a bit more experienced with it. I'd suggest, if we can, we put anything around the ping that might be reusable into the site.js file.

When I tested locally the address change didn't seem to result in the lat/long updating, but I might have been unlucky. I can try and pull later and check again.

**Comment by tonysurma** [comment]
@dpaquette can you take a review?

**Comment by dpaquette** [comment]
Sure, I will review either tonight or tomorrow

**Pull request merged**
