### PR TITLE
Adding multiple goals for campaigns

### PR DESCRIPTION
**Pull request by mipre100**
WIP: Have made changes to DB and added migrations to allow many goals per campaign, and getting the code to compile. Still need to update the views and add code to allow CRUD for goals within the campaign.  Also need to consider how we might show a consolidated goal view.

### CODE REVIEW

**Comment by mipre100** [comment]
Relates to issue #38

**Comment by stevejgordon** [comment]
Thanks @mipre100 for getting this started. Once you'r further along let us know when you want a review. 

Just a quick thought - I am wondering if the term CampaignImpact is a bit confusing. For me personally, "goal" makes more sense.

@tonysurma - Have we specifically decided we prefer to use CampaignImpact rather than Goal in our domain? Might be the time to make a change if we determine that better describes this entity?

**Comment by mgmccarthy** [comment]
@stevejgordon, I like "goal" as well

**Comment by mipre100** [comment]
I have now completed the work to add multiple goals.

Goals are shown down the left hand side of the campaign screen, with the existing thermometers or plain text goals:
image

On the campaign edit screen, multiple goals are shown on the details page, with options to create a new goal, or edit or delete an existing goal:
image

The New/Edit  Goal page handles both numeric and text goals, with the GoalType dropdown showing/hiding the fields as appropriate:

image
image


As part of this work I have also renamed the `CampaignImpact` entity to `CampaignGoal`.

@stevejgordon Can you have a look through this and let me know if there is anything you think should be improved.

**Comment by tonysurma** [comment]
thanks @mipre100 post @stevejgordon review we can merge.

**Comment by stevejgordon** [comment]
I didn't get chance to pull the code at lunch today, but I'll try to do so this week and provide feedback. Thanks @mipre100 for the PR. The screenshots and detail is great to help reviewers know what to look at and what you've done.

**Pull request merged**
