### PR TITLE
Created list page for event and campaign manger invites

### LINKED ISSUE #1887: Add ManagementInvite Lister
Breakout from #1804

Add a page for org admins to view status of all management invites. This should be a lister page that an org admin can view, showing all invites organised by type.

Should show the date sent, status etc.

NOTE: Once access is granted to other user levels, such as event managers, we may need to limit the types of invite we show. A single view hopefully can handle this though.

### PR DESCRIPTION
**Pull request by mk0sojo**
List page under route /admin/invite
For the links to invite details to work PR #2009 needs to be merged.

closes #1887

### CODE REVIEW

**Comment by MisterJames** [comment]
@mk0sojo thanks for this! I'll merge it in once we get #2009 wrapped up. 

Cheers.

**Comment by MisterJames** [comment]
@mk0sojo looks like a few conflicts after merging #2009. Can you do a quick update for us?

**Comment by mk0sojo** [comment]
Ok, I will have a look tonight or tomorrow.

Thanks.

**Comment by mk0sojo** [comment]
Should be ok now.

**Comment by MisterJames** [comment]
@mk0sojo So, this has been a while, but the other bits are merged in and this is close now. I tried to resolve the merge conflicts, but there are errors and possibly some incorrect types (see `InviteController` in particular). If you can get this one to build/pass locally, please update the PR and I'll merge it with priority.

Thanks!

**Comment by mk0sojo** [comment]
Sorry @MisterJames . I missed this comment. The merge problem should be fixed now, but there is a problem with the build server that @VishalMadhvani fixed so it should be working now.

**Comment by dchristensen** [comment]
@mk0sojo, with the fixes implemented by @VishalMadhvani you should be able to rebase your branch on top of master and that should fix the AppVeyor build.

**Comment by mk0sojo** [comment]
@MisterJames Is this one ready to merge or are you waiting for me to do something?

**Pull request merged**
