### PR TITLE
You can create an Itinerary in the past #1490

### PR DESCRIPTION
**Pull request by HamidMosalla**
Changed the `ItineraryEditModelValidator` class to invalidate the Model based on conditions discussed [here](https://github.com/HTBox/allReady/issues/1490), also set the Scheduled Date to current date in the view and edited existing unit tests and adding new one for our new condition in `ItineraryEditModelValidator`.

Closes: #1490

### CODE REVIEW

**Comment by HamidMosalla** [comment]
@mgmccarthy Here is my crude and un-gnarly?!? implementation with some problems: 

```
    public class ItineraryEditModelValidator : IItineraryEditModelValidator
    {

        private DateTimeOffset AdjustToTimezone(DateTimeOffset dateTimeOffset, TimeZoneInfo timeZone)
        {
            return new DateTimeOffset(dateTimeOffset.DateTime, timeZone.GetUtcOffset(dateTimeOffset.DateTime));
        }

        public List<KeyValuePair<string, string>> Validate(ItineraryEditViewModel model, EventSummaryViewModel eventSummary)
        {
            var result = new List<KeyValuePair<string, string>>();

             TimeZoneInfo currentTimeZone = TimeZoneInfo.FindSystemTimeZoneById(eventSummary.TimeZoneId);
            var adjustedDateTimeOffSet = AdjustToTimezone(DateTimeOffset.Now, currentTimeZone).Date;

            if (model.Date < eventSummary.StartDateTime.Date)
            {
                result.Add(new KeyValuePair<string, string>(nameof(model.Date), "Date cannot be earlier than the event start date " + eventSummary.StartDateTime.Date.ToString("d")));
            }

            if (model.Date > eventSummary.EndDateTime.Date)
            {
                result.Add(new KeyValuePair<string, string>(nameof(model.Date), "Date cannot be later than the event end date " + eventSummary.EndDateTime.Date.ToString("d")));
            }

            if ((eventSummary.StartDateTime.Date < adjustedDateTimeOffSet) && (model.Date < adjustedDateTimeOffSet))
            {
                result.Add(new KeyValuePair<string, string>(nameof(model.Date), "Date cannot be earlier than the current date if the event start date is in the past " + eventSummary.EndDateTime.Date.ToString("d")));
            }

            return result;
        }
    }
```
The problem is `model.Date` is of type `DateTime` and even if it was `DateTimeOffSet` we don't have the `TimeZoneId` to use the `AdjustToTimezone` attribute, but we could at least pass it to `AdjustToTimezone` private method, I don't know maybe something like this will work?
```
            var currentUtcDate = TimeZoneInfo.ConvertTimeToUtc(model.Date, currentTimeZone);
            var adjustedDateTimeOffSetForModel= AdjustToTimezone(currentUtcDate, currentTimeZone);
```
And we could use the `adjustedDateTimeOffSetForModel` instead of `model.Date` for comparison, I'm not sure.

**Comment by mgmccarthy** [comment]
@HamidMosalla, actually, the date/time comparisons in this whole validator probably need to be looked at. When I've had a chance to talk to @dpaquette, I'll let you know. Sorry this is holding up your PR, but you might have found a larger problem here where all validators we have in the system that are "downstream" of the `AdjustToTimeZone` model binder might need to compensate for the TimeZoneId so the comparisons work.

I'll be trying to run some tests today to confirm this.

**Comment by mgmccarthy** [comment]
@HamidMosalla, I just amended my previous comment... basically, b/c we're retrieving the Event's Start/EndDateTime from the `EventSummaryQueryHandler`, these two values have already been converted to the Event's time zone before they were written to the db.

Because `ItineraryEditViewModel.Date` is `DateTimeKind.Unspecified`, we need to convert it to the Event's time zone id before we do any comparisons. Because of this, taking the added functionality for this PR addressing Issue #1490 off the table, this validator is broken.

Here is an implementation of how to update the validator to make sure we're comparing DateTime in the same time zone:
```
public class ItineraryEditModelValidator : IItineraryEditModelValidator
{
    public List<KeyValuePair<string, string>> Validate(ItineraryEditViewModel model, EventSummaryViewModel eventSummary)
    {
        var result = new List<KeyValuePair<string, string>>();

        var itineraryDateConverted = ConvertIntineraryDateToEventsTimeZone(model.Date, eventSummary.TimeZoneId);

        if (itineraryDateConverted.Date < eventSummary.StartDateTime.Date)
        {
            result.Add(new KeyValuePair<string, string>(nameof(model.Date), "Date cannot be earlier than the event start date " + eventSummary.StartDateTime.Date.ToString("d")));
         }

        if (itineraryDateConverted.Date > eventSummary.EndDateTime.Date)
        {
             result.Add(new KeyValuePair<string, string>(nameof(model.Date), "Date cannot be later than the event end date " + eventSummary.EndDateTime.Date.ToString("d")));
        }

        return result;
    }
        
    private static DateTimeOffset ConvertIntineraryDateToEventsTimeZone(DateTime itineraryDate, string eventsTimeZoneId)
    {
        var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(eventsTimeZoneId);
        var utcOffset = timeZoneInfo.GetUtcOffset(itineraryDate);
        return new DateTimeOffset(itineraryDate, utcOffset);
    }
}
```

I'd go ahead and roll these changes into this PR, then we can tackle how to handle the "now" comparison against the `DateTimeKind.Unspecified` value in `ItineraryEditViewModel.Date`.

Sound good?

**Comment by HamidMosalla** [comment]
@mgmccarthy No worries about the PR, I was just pocking around the code base trying to understand what @dpaquette  did with model binder which was interesting, I was curious what could work in this situation, so I thought I share what I came up with.

**Comment by dpaquette** [comment]
Yeah this situation is a little different since we are comparing a DateTimeOffset with a Date (with no Time). Having proper structures to represent these different types would be one of the big advantages to moving to NodaTime.

**Comment by HamidMosalla** [comment]
@mgmccarthy  Sound great, I'll write the "now" comparison around your implementation.

**Comment by HamidMosalla** [comment]
Now, for the now comparison, 

```
            var currentDateTimeConverted = ConvertIntineraryDateToEventsTimeZone(DateTime.Now, eventSummary.TimeZoneId);

            if ((eventSummary.StartDateTime.Date < currentDateTimeConverted) && (itineraryDateConverted < currentDateTimeConverted))
            {
                result.Add(new KeyValuePair<string, string>(nameof(model.Date), "Date cannot be earlier than the current date if the event start date is in the past " + eventSummary.EndDateTime.Date.ToString("d")));
            }
```
And maybe we could rename the `ConvertIntineraryDateToEventsTimeZone` to something more generic, and also I assumed that we can pass the same `TimeZoneId` to `ConvertIntineraryDateToEventsTimeZone` which I might be wrong, also In the `Details` view of the Event controller I set the Scheduled date input to:

`<input class="form-control" id="createItineraryModal-date" asp-for="NewItinerary.Date" name="@nameof(Model.NewItinerary.Date)" value="@DateTime.Now.ToString("yyyy-MM-dd")">`
which I don't know if it's what we want, maybe `DateTime.UtcNow`?

**Comment by mgmccarthy** [comment]
@HamidMosalla, hold off on the "now" unit tests. @dpaquette is going to get a chance to go over what is at this point, a bigger concern than just this one validator.

Don't worry about converting ConvertIntineraryDateToEventsTimeZone to be more generic for now....

**Comment by HamidMosalla** [comment]
@mgmccarthy I hold off any further commits to this RP until validator problems are addressed on the project level, if there is anything else, please let me know.

**Comment by tonysurma** [comment]
@mgmccarthy @dpaquette any update on how @HamidMosalla can close this out?  Thanks

**Comment by dpaquette** [comment]
Sorry it's been a busy week. I will try to look at this tomorrow

**Comment by tonysurma** [comment]
@dpaquette no worries

**Comment by dpaquette** [comment]
Yeah this should be good. I would like it to be easier to do this comparison so I will be writing some comparison functions later on but that will be a separate task.

Thanks @HamidMosalla and sorry for the delay in reviewing this

**Pull request merged**
