### PR TITLE
Created Git Usage Guide

### LINKED ISSUE #1273: Create a Git usage guide
As I have run or participated in Hackathons for allReady, one of the consistent issues that I have run into is people not understanding how to use Git.    Many times we have had participants that it is their first time using Git or Github.  It would be nice to have a guide that walks them through the Git process for forking, cloning, commiting, pushing, submitting PR, and syncing fork with HTBox/allReady.  

Just a basic guide that walks them through what they need to know to be a successful contributor.

### PR DESCRIPTION
**Pull request by digitaldrummerj**
Initial revision of a git usage guide that walks a contributor through using Git to contribute changes to allReady.

Closes #1273

### CODE REVIEW

**Comment by tonysurma** [comment]
@stevejgordon or @dpaquette can you take a peek at this as we use your blog posts for a lot of this in the past

**Comment by stevejgordon** [comment]
@tonysurma Looks very comprehensive and worth having. I would question whether this goes in the docs here or in the htbox.github.io project? We have some info in each at the moment and I guess it would be good to consolidate in a single place?

@digitaldrummerj My only comment is whether the npm install and bower install are really necessary. I don think I've had to do those manually, although I'm always in VS 2015.

**Comment by digitaldrummerj** [comment]
@stevejgordon I can take out the npm and bower commands.  I always forget the Visual Studio will do those for you if you have not already done them.   

@stevejgordon  and @tonysurma I didn't even know about http://htbox.github.io .  The info there is a little sparse and I am not sure the other docs in this repo even reference that site.  I agree that putting them all in one place is the best way.  Just let me know where you want me to put this guide.

**Comment by tonysurma** [comment]
ping @BillWagner as he did the htbox.github.io part

**Comment by stevejgordon** [comment]
For reference I've just finished reviewing and tweaking my blog post about GitHub etiquette which is available at https://www.stevejgordon.co.uk/github-contributor-tips-tricks-gitiquette

**Comment by digitaldrummerj** [comment]
@stevejgordon I removed the npm and bower install information.  I also added an additional links section with the links that have been mentioned in the gh issue and this PR.

**Comment by dpaquette** [comment]
@digitaldrummerj This is an excellent and very detailed guide. Thank you for writing it! I like that you are setting up git from scratch and using 100% command line tooling for it. It's nice to see that all put together in a step-by-step guide.

I do worry a little however that the command line approach might scare away some first-time contributors who are completely new to git. In the guide I had written, I used GitHub for Windows since it does the work of setting up the git client for you and makes cloning repos to your desktop very easy. 

**I don't think we should change what you did here because it is an excellent guide**. Maybe we can have a link to an alternate document that shows how to do all the same things using GitHub for Windows.

For reference, here is my article: http://www.davepaquette.com/archive/2016/01/24/Submitting-Your-First-Pull-request.aspx

**Comment by tonysurma** [comment]
going to merge for now and we can always refactor to htbox.github.io later

**Pull request merged**
