### PR TITLE
Make code async all the way

### PR DESCRIPTION
**Pull request by SeanFeldman**
Hopefully it's not too horrible :worried: 
@dpaquette @MisterJames  Please review.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Please update https://github.com/HTBox/allReady/issues/549 when PR is merged

**Comment by mheggeseth** [comment]
FYI, the "walls of red" seem to just be line ending formatting. Thanks @SeanFeldman for fixing that.

**Comment by tonysurma** [comment]
Thanks @SeanFeldman.  @mheggeseth is this good to go?

**Comment by mheggeseth** [comment]
I don't see anything concerning, but I'd be more comfortable if @dpaquette or @MisterJames gave the OK. I don't have a lot of experience with C# async.

**Comment by BillWagner** [comment]
Overall, the Async implementation is really good. Thanks @SeanFeldman for all the work. I had a few specific comments on the implementation.

**Comment by SeanFeldman** [comment]
@BillWagner thank you for prompt review. I'll get home and address all comments.

**Comment by BillWagner** [comment]
@SeanFeldman and I discussed the changes, once the merge conflicts are fixed, :shipit:

**Comment by SeanFeldman** [comment]
Had to change how mock is created to reflect async changes.

**Pull request merged**
