### PR TITLE
stubbing out unit tests for ActivityController

### LINKED ISSUE #647: stubbing out unit tests for ActivityController
@tonysurma please assign to me. I'm currently working on this. Part of #620

### PR DESCRIPTION
**Pull request by mgmccarthy**
Fixes #647

### CODE REVIEW

**Comment by BillWagner** [comment]
@mgmccarthy I'll keep reviewing the code, but can you rebase and resolve conflicts?

**Comment by mgmccarthy** [comment]
I see where some conflicts are in my existing PR's... let me see what I can do.

**Comment by mgmccarthy** [comment]
@BillWagner, because we have two ActivityAdminControllers in the system:
AllReady.Areas.Admin.Controllers.ActivityController
AllReady.Controllers.ActivityController

also, the names of the controllers .cs files on disk do not always match the name of the controller class name which is even more confusing

because of this confusion, unit tests were added to the wrong unit test file for the wrong controller. I've corrected and hopefully we'll get at clean build, but I'd recommend renaming all controllers in the /Areas/Admin with the word "Admin" so we don't have any more mixups.

**Comment by mgmccarthy** [comment]
@BillWagner the build succeeded, you can merge when ready

**Comment by BillWagner** [comment]
Finished the review as @mgmccarthy managed the merge.

**Pull request merged**
