### PR TITLE
Change SampleData Generator to save in a persisted local database

### PR DESCRIPTION
**Pull request by bcbeatty**
Change SampleData Generator to save in a persisted local database
Change Skill.ParentSkillId to allow nulls, this was preventing adding a skill

### CODE REVIEW

**Comment by mheggeseth** [comment]
@bcbeatty Thanks for doing this! Just an FYI: to avoid the dreaded "wall-of-red" we're normalizing on Tab==4 spaces line indentation (the VS default).

**Comment by bcbeatty** [comment]
That's my settings Tabs==4, keep tabs

**Comment by mheggeseth** [comment]
We are using "Insert spaces" instead of "Keep tabs". :smiley:

**Comment by mheggeseth** [comment]
I noticed a couple Skill CRUD fixes that'll need to be made with this. This fixes creating/editing a skill with no parent as well as properly orphaning child skills when their parent is deleted.  https://github.com/mheggeseth/allReady/commit/942d45a5edfc543dc2adfc7979b52591fbf3ec0f Feel free to pull them into your branch.

**Pull request merged**
