### PR TITLE
Task StartDateTime and EndDateTime is no longer nullable.

### PR DESCRIPTION
**Pull request by VishalMadhvani**
PR for Issue #939

### CODE REVIEW

**Comment by tonysurma** [comment]
Thanks @VishalMadhvani

Looks likes  there  is a failing unit test about null end times :)

**Comment by VishalMadhvani** [comment]
My bad 👎  forgot to run tests before check in.
Now fixed :)

**Comment by tonysurma** [comment]
Thx!

**Comment by tonysurma** [comment]
Just reviewed and looks like you caught all the cases - thanks!

**Pull request merged**
