### PR TITLE
Merge into InMemoryContextTest:

### PR DESCRIPTION
**Pull request by robrich**
InMemoryContextTestBase and InMemoryContextTestAsync are merged into InMemoryContextTest

### CODE REVIEW

**Comment by tonysurma** [comment]
got a 👍 from @mgmccarthy so if you can rebase I will merge it @robrich thanks!

**Comment by robrich** [comment]
Rebased.

**Comment by tonysurma** [comment]
@robrich thx, looks like a post rebase build error occurred https://ci.appveyor.com/project/HTBox/allready/build/1.0.0.1608.master#L772

**Comment by robrich** [comment]
Good catch.  Such is the nature of trying to eliminate technical debt: some use it on new code while the PR is waiting.  :D

**Pull request merged**
