### PR TITLE
Organize view model directory

### LINKED ISSUE #857: ViewModel organization under "ViewModels" directory
first off, this is low priority, but I wanted to record it while I was thinking of it.

we currently have come classes in here (AccountViewModels) that contain multiple ViewModel classes for the same controller.

We should organize the ViewModels folder to have the name of the controller as a directory, and then all relevant ViewModel classes go under that directory. The View folder is organized in such a way.

Using AccountViewModels as an example. Here is what it looks like right now:
image

This is what I'm proposing it would look like:
image

### PR DESCRIPTION
**Pull request by mgmccarthy**
Fixes #857

### CODE REVIEW

**Comment by mgmccarthy** [comment]
this looks like a LOt of changes... about half of the changed files are a result of running "remove unused usings" across the entire /Web/AppReady proejct. The other half are the relocation/namespace changes for ViewModel organization

**Comment by tonysurma** [comment]
@mgmccarthy can you rebase off of your other PR now that I merged and I will pull this in while there aren't a lot of outstanding PRs

**Comment by mgmccarthy** [comment]
@tonysurma I'll take care of it tonight

**Comment by tonysurma** [comment]
Thx!

**Pull request merged**
