### PR TITLE
Remove preferred email and preferred phone number from task signup

### LINKED ISSUE #894: Remove PreferredEmail and PreferredPhoneNumber on TaskSignup/EventSignUp
this results in handlers needing to first check if PreferredEmail/PreferredPhoneNumber is null, and if it is, to include User into the query in order to get at ApplicationUser's Email and PhoneNumber values (which also could be null).

We go through an email vaildation for ApplicationUser email (there is EmailConfirmed field) to validate the user's email, but do we also validate email's/phone numbers added to TaskSignup?

### PR DESCRIPTION
**Pull request by mgmccarthy**
Fixes #894

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames 

part of this PR is that we'll use the user provided email address and phone number instead of the now-defunct PrefferedEmail and PreferredPhoneNumber for communication.

That being said, MessageTaskVolunteersCommandHandlerAsync only sends messages to users where their email and phone numbers are confirmed. If those are not confirmed, then messages are never sent.

If we're going to align with using the user-provided email/phone when they register with the site, then the rest of our code should follow suit, and attempt to send messages via phone/email even if neither of those items are confirmed yet.

**Comment by tonysurma** [comment]
@mgmccarthy needs rebase and @MisterJames let me know if you can review.  Thanks

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames I just rebased this then pushed and got a successful build, but it looks like there are still conflicts?

**Comment by tonysurma** [comment]
It is tagging 3 files as conflicts

AllReadyApp/Web-App/AllReady.UnitTest/Areas/Admin/ViewModels/Validators/Task/TaskEditModelValidatorShould.cs 
AllReadyApp/Web-App/AllReady/Areas/Admin/Controllers/TaskController.cs 
AllReadyApp/Web-App/AllReady/Areas/Admin/ViewModels/Validators/TaskEditModelValidator.cs

But not sure

**Comment by mgmccarthy** [comment]
@tonysurma, it looks like someone merged another PR and that's what caused the conflict, I'm taking a look now

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames rebased again and ready for review.

**Comment by tonysurma** [comment]
@mgmccarthy the open source sorting hat  🎩  has chosen the house of 'Mergerin' for you again..

After a rebase I will merge this in

**Comment by mgmccarthy** [comment]
@tonysurma, at this point, the sorting :tophat: could have put me in Slytherin, and I would have been ok with it ;)

gonna rebase again...

**Comment by mgmccarthy** [comment]
@tonysurma, :shipit: please :pray:

**Pull request merged**
