### PR TITLE
Fixe Bug 1340

### LINKED ISSUE #1340: I managed to cause an error trying to manage my external logins
From http://allready-d.azurewebsites.net/Manage
click on Manage to reach the following page which contains the deeply un user-friendly error. 
http://allready-d.azurewebsites.net/Manage/ManageLogins
``The page cannot be displayed because an internal server error has occurred.
An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.``

``Generated Code``

``The type or namespace name 'ManageLoginsViewModel' could not be found (are you missing a using directive or an assembly reference?)
    public class _Views_Manage_ManageLogins_cshtml : Microsoft.AspNetCore.Mvc.Razor.RazorPage<ManageLoginsViewModel>
The type or namespace name 'ManageLoginsViewModel' could not be found (are you missing a using directive or an assembly reference?)
        public Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<ManageLoginsViewModel> Html { get; private set; }``

### PR DESCRIPTION
**Pull request by mgmccarthy**
Fixes #1340 and #1322

### CODE REVIEW

**Comment by mgmccarthy** [comment]
Hmmm. I made no changes to PostCodeGeo table and I didn't do anything with migrations:

image

**Comment by stevejgordon** [comment]
@mgmccarthy This same test failed for one of my recent PRs. @tonysurma was able to retry the build and it works 2nd time. Like you, I was not getting a failure locally.

**Comment by mgmccarthy** [comment]
Thanks @stevejgordon. @tonysurma can you retry this build please?

**Comment by tonysurma** [comment]
Will do as well as log an issue to figure out why it fails sometimes

**Pull request merged**
