### PR TITLE
Fixes #2348 Campaign Start/End Date does not appear correctly on Admin/Event/Create page

### LINKED ISSUE #2348: Campaign Start/End Date does not appear correctly on Admin/Event/Create page
Encountered this while working on #2345.  

The **Admin/Event/Create** page shows 
image

While **Admin/Campaign/Details** shows
image

### PR DESCRIPTION
**Pull request by c0g1t8**
Self explanatory

### CODE REVIEW

**Comment by c0g1t8** [comment]
@jonparker It's nice to know that someone else is still out there :)

**Comment by jonparker** [comment]
I don't have permission to merge the PR though

**Comment by c0g1t8** [comment]
Aggregated into #2352.  Closing this PR.

**Comment by c0g1t8** [comment]
This fix has been aggregated into #2352.  Closing this PR.

**Comment by c0g1t8** [comment]
Fix in #2352.  Closing this PR.

**Pull request closed without merging**
