### PR TITLE
WIP [need feedback] - Campaign thermometer

### LINKED ISSUE #250: Add thermometer rendering based on current and target values
Two aspects to this:
 - [ ] data entry on the Campaign Edit page
 - [ ] rendering the thermometer on the public campaign page (for numeric impact types)

From #35.

### PR DESCRIPTION
**Pull request by MisterJames**
- updated models
 - updated repository
 - updated views
 - added new `ImpactType` enum
 - added migration

Resolves #250

### CODE REVIEW

**Comment by mheggeseth** [comment]
Are two `_CampaignImpact.cshtml` partial views necessary? Their content is identical except for the model type.

**Comment by BillWagner** [comment]
@MisterJames Can you rebase and remove conflicts?

**Comment by MisterJames** [comment]
@mheggeseth no, the two aren't required and I'm actually wanting to head in a different direction here as well. However, for now this is just enough to meet the requirement. I actually used existing plumbing to pull this together. 

In the longer term I would like to see a more permanent solution that could be used inside and ouside of the site, along the lines of #327.

**Comment by MisterJames** [comment]
@dpaquette is there any chance you would have a minute to look at this? I am running into the same issue again with the migration (removing a column and table, then several errors after migrations run the second time).

**Comment by MisterJames** [comment]
@BillWagner I have a migration on this branch that removes a table. It seems to run fine the _first_ time, but subsequent runs produce EF errors. It may be related to a bug in EF migrations, but I haven't yet got solid proof yet. Please don't merge this guy yet!

**Comment by dpaquette** [comment]
I think the problem is because there was another migration that was merged to master.  Try following:

-Checkout and update master.
-Delete and recreate your database by re-running the app.
-Checkout your branch and rebase with master
-Delete your migration and the model snapshot
-Recreate your migration

In theory everything should work.

**Comment by BillWagner** [comment]
@MisterJames @dpaquette Once we know what does work, can you send me notes (in whatever short form works) and I'll add it to the contributing.md for all our projects.

**Comment by MisterJames** [comment]
@dpaquette So there were two small things I had to do differently:

 - Checkout and update master.
 - Delete and recreate your database by re-running the app.
 - *Take a copy of the `AllReadyContextModelSnapshot.cs` file*
 - Checkout your branch and rebase with master
 - Delete your migration and *replace the model snapshot with the one from master*
 - Recreate your migration
 - Run the app

If you have also made changes to the sample data generator and would like to see that data, from this point you would need to delete your DB and re-run the app. This would re-create your db and all migrations should work.  This is also a good thing to do (del + regen) before shipping anything up to a PR, just to ensure that any developers that pull your code for the first time can have a seamless experience.

@BillWagner should be good to go here, with the above directions, for some guidelines.

**Comment by dpaquette** [comment]
Yah! :shipit:

**Pull request merged**
