### PR TITLE
1877 logout button ui

### LINKED ISSUE #1877: navbar - make logoff as an item 'under' your user name [JT]
from a UI point of view don't take space home navbar and make it a float sub menu for logoff (can later be used for other items as well)

### PR DESCRIPTION
**Pull request by dchristensen**
Fixes #1877

I included changes to the CSS for the `.dropdown-admin` class so that those styles are applied by default to all dropdowns in the nav.

I updated the UI tests based on patterns used in other tests, but I have been unable to actually run them due to the issues in #1938

### CODE REVIEW

**Comment by tonysurma** [comment]
@stevejgordon can you take a quick peek but I looked and it looks great to me @dchristensen

**Comment by tonysurma** [comment]
just checked with @stevejgordon to do a second review if he can, if not I will merge given my review.

@dchristensen thanks for your patience, can you rebase on the current master so we can merge this in.

Thanks again

**Comment by dchristensen** [comment]
@tonysurma rebased, should be good to go now

**Comment by stevejgordon** [comment]
@tonysurma I'm not up on f# and the integration test stuff, but the UI changes look okay from a quick glance. Not sure on the vs code inclusion best practices. We have a .vscode folder under the Web-App\AllReady folder for that specific project. Not sure if we can/should have these located in each project or at the higher level. I'd need to investigate that.

**Comment by dchristensen** [comment]
@stevejgordon @tonysurma ahh, those pesky .vscode files were not supposed to be included in this PR.  I can remove them before merging if you'd like.

**Comment by tonysurma** [comment]
if you don't mind lets remove them for now.  We need to figure out if they need to be removed/excluded or updated.  They were originally from an update to support mac but not sure if they are needed 'like' that or 'common' in the repository.

Thanks again

**Comment by dchristensen** [comment]
@tonysurma Files removed.

**Comment by dchristensen** [comment]
@stevejgordon Thanks for taking a look.  Looks like I lost some of my changes in the rebase.  Should be good to go now.

**Comment by c0g1t8** [comment]
Just tested this in Edge 😦 **Log off** text is not visible.

In Edge
image

In Chrome
image

**Comment by c0g1t8** [comment]
@dchristensen Did some more testing this morning after rebooting.  I can't seem to reproduce this problem in Edge.

**Pull request merged**
