### PR TITLE
Install and Configuration Guide for Contributors

### LINKED ISSUE #1274: Create install guide for required software
As I have run or participated in hackathons for allReady I have gotten a bunch of questions on exact install steps for all of the required software.  Right now there is not a walk through guide and only a listing of software to install.  A lot of times participants have not used node, npm, bower, ionic, etc so they are not sure how to get them installed.  A walk through guide would make it quicker for them to get everything installed and would ensure that everyone has the same setup.

### LINKED ISSUE #1281: Git Guide: Change git download link
A few people that I have had review the Git guide suggested to point at the Git command line download link instead of pointing at the Git book install guide.  The link is [https://git-scm.com/downloads](https://git-scm.com/downloads)

### LINKED ISSUE #1282: Git Guide: markdown saw the link https://github.com[User Name] as a link
markdown saw the link https://github.com[User Name]/allReady  as a instead of text like it should be.

### LINKED ISSUE #1287: Git Guide: proxy configuration missing http.proxy
the command git config --global --add [Your Proxy Server and Port] should be git config --global --add http.proxy [Your Proxy Server and Port]

The command is missing the http.proxy that the 2nd command has.

### PR DESCRIPTION
**Pull request by digitaldrummerj**
The install and configuration guide for contributors will walk a contributor through all of the steps needed to get a development machine up and running for allReady.  The guide is functionally complete  and I made it as I was doing all of the installs/configurations but I have not had a chance to go back through and proof read the guide again.

The install guide also makes several edits to the Git guide as the portions of the Git guide there were install and configuration related have been moved this guide instead.  The git guide references the install guide in order to get Git installed/configured as well as getting the source code.

Closes #1274 
Closes #1287 
Closes #1282 
Closes #1281

### CODE REVIEW

**Comment by digitaldrummerj** [comment]
@tonysurma I am ready for the contributor install guide to be reviewed

**Comment by tonysurma** [comment]
@digitaldrummerj great.  @stevejgordon @mgmccarthy @MisterJames @dpaquette if any/all of you can take a review that would be great - thanks again @digitaldrummerj

**Comment by stevejgordon** [comment]
@tonysurma This looks fantastic. It may be a bit daunting to newcomers due to it's shear size but I think the detail included is very valuable.

I'm not 100% sure on the npm install stuff. Does VS not do that for you as part of it's install? I don't recall having to manually install it but I could very well be wrong on that. I haven't got a clean machine to test though.

Thanks @digitaldrummerj - You are now crowned documentation king! :crown:

**Comment by dpaquette** [comment]
@stevejgordon yes, if you are using Visual Studio 2015, all the NPM and Bower packages are installed automatically

**Comment by dpaquette** [comment]
@digitaldrummerj this is an amazingly detailed and will put together document. Great job putting it together

**Comment by digitaldrummerj** [comment]
@dpaquette and @stevejgordon   For the Node and Npm installs, Visual Studio will install node for you but I have had a lot of issues with the version it installs.  Up until recently the version installed was pretty old (0.12).  I believe they have recently update it to use Node 4.x.    However, even with Node 4.x it still comes with npm 2.x which tends to cause path length issues with larger dependency trees.  Npm 3.x flattens the dependency tree so it is far less likely you will run into path length issues.  As well Visual Studio will sandbox node so it is not available on the command line which means tools like cordova and ionic are not available on the command line.  

In the guide Visual Studio does take care of installing the npm and bower packages when they open the solutions.  The reason to install ionic, cordova, gulp-cli, and bower globally is so that the ionic and cordova command lines are available with all of the tools that they need.  When you run ionic serve it will run a gulp task as part of that so you need gulp-cli available.

**Pull request merged**
