### PR TITLE
2nd attempt to correct image urls  both in Campaign.md and UserDocTem…

### PR DESCRIPTION
**Pull request by DanKline**
...plate.mdt.  To use the template, copy it to the docs/user_documentation directory in the local file explorrer and rename it to the module desired, but with the md extension.  You can then edit it with your favorite markdown editor.

### CODE REVIEW

**Comment by DanKline** [comment]
I'm not sure why this build failed.  There were no conflicts and everything is synced and builds locally.

**Comment by MisterJames** [comment]
@DanKline Can you rebase to master (again!)? I think it should be pretty straightforward, and then your commit/push should push AppVeyor into submission.  Thanks!

**Comment by DanKline** [comment]
I’ve never done it … but let me try.  Thanks.  I’m looking forward to continuing with the documentation.

**Comment by DanKline** [comment]
I'm stuck on this rebase.  Between the post-surgical fog and my lack of experience, I just don't  "git" Git.  My rebases never pull the 60 commits into my forked repo on Github.  I'm about to give up and delete my fork and refork from HTBOX, then just make my few changes.  Are there any caveats to this approach?

**Comment by dchristensen** [comment]
@DanKline  it sounds like you are not rebasing your fork against the HTBox master.  To do that you will need to [setup a remote for HTBox master](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and then [sync your fork with HTBox upstream](https://help.github.com/articles/syncing-a-fork/).  _(Note: you should be able to use `git rebase` instead of `git merge` when syncing to do an actual rebase instead of merge)_

**Comment by DanKline** [comment]
PR# 2078 is finally ready for merge.  I've corrected the conflicts.  I'm not sure how to resubmit the pull request.

**Pull request merged**
