### PR TITLE
mobile app converted to true ionic project.

### PR DESCRIPTION
**Pull request by digitaldrummerj**
Removed login page since the login was not used with any of the
functionality.

converted to a true ionic project that can be used either from visual studio or the command line.  

fixes https://github.com/HTBox/allReady/issues/1082
fixes https://github.com/HTBox/allReady/issues/1081
fixes https://github.com/HTBox/allReady/issues/1076

https://github.com/HTBox/allReady/issues/1091

### CODE REVIEW

**Comment by tonysurma** [comment]
@digitaldrummerj is this good to go (assuming build works etc.)?  Thanks

**Comment by tonysurma** [comment]
also anything special a VS2015 community edition Update 3 user would need to know to open/work on this? (I assume install cordova stuff that comes when you click cordova in install, but anything special to check/uncheck?)  Thanks again

**Comment by digitaldrummerj** [comment]
The biggest thing is to install the npm packages that ionic requires by running.  All of the Visual Studio stuff is still the same after that.  

```
npm install -g cordova ionic gulp bower
```

**Comment by digitaldrummerj** [comment]
@tonysurma this is good to go.  It has the same functionality as the current mobile app which is to view events, event details, and check in with the QR code scan.  I removed the login screen since none of the existing functionality required it.

**Pull request merged**
