### PR TITLE
adding unit tests for HomeController

### PR DESCRIPTION
**Pull request by mgmccarthy**
Issue #575. Also done in HomeController. 
- deleted un-used ViewData["Message"] code from Aesop and About action methods 
- deleted the Contact() action method.

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@tonysurma, it looks like AppVeyor is a cloud-based build server? Looks like my build failed, but when looking at the url that the Details linked links to, it's a bunch of output, and i really can't find what the error is.

Would this be directly related to any other set up items i haven't done? For example, I have not set up a free Azure account yet, but I'm not too sure if my commit, and subsequent build is going to try to use Azure as part of the build?

If this isn't your area, can you point to someone who can let me know how i can fix this?

**Comment by tonysurma** [comment]
pinging @BillWagner and @dpaquette who have been on this.  Something is up but we don't know what (at least that I know of)

**Comment by mgmccarthy** [comment]
Just wanted to make sure it's not something I inadvertently caused. I ran all unit tests locally and smoke tested via F5. Everything looked good, so I submitted by PR. Thanks.

**Comment by mgmccarthy** [comment]
looks like my PR for Issue #578 was included in this PR, which originally from Issue #575, adding unit tests to HomeController. As a Git and GitHub newbie, I need to figure out how to separate these two into two separate pull requests. Sorry about that.

**Comment by tonysurma** [comment]
@mgmccarthy   please rebase off of master as we now have a fix for the build/test issues!

For reference on rebasing this page helps (replace upstream with HTBox in examples) https://robots.thoughtbot.com/keeping-a-github-fork-updated

**Comment by mgmccarthy** [comment]
@tonysurma, I'm not comfortable enough with git to rebase. Looks like rebase done wrong can go really badly. I don't know the command line for Git at all, and I've only ever worked with git commands via VS 2015 Team Explorer.

That being said there is a "rebase" option on these tools, but I have no ideas how to "rebase off of master" using them. Not too sure what to pick on this UI. All I know is I did not create a feature branch locally when doing my changes (I committed all changes to master locally). When I was ready to commit my changes to the online repo, I'd push (push to origin?) and it updated my forked repo, and then also updated HTBox/allReady for the open PR.
image


I'm (embarrassingly) going to need help with this...

**Comment by tonysurma** [comment]
no worries @mgmccarthy .  cc @BillWagner

**Comment by BillWagner** [comment]
@mgmccarthy I understand. The git command tools are not that hard once you've used them.  This article does a good job of explaining the process from the command line: https://robots.thoughtbot.com/keeping-a-github-fork-updated

Look under the "Updates" section. Here's step by step instructions for the AllReady repo:

First, run "git remote -v". This command lists all the remote repositories that are related to your working directory on your disk. You'll see output something like this:

C:\Users\billw\Documents\GitHub\allReady [master]> git remote -v
HTBox   https://github.com/HTBox/allReady.git (fetch)
HTBox   https://github.com/HTBox/allReady.git (push)
origin  https://github.com/BillWagner/allReady.git (fetch)
origin  https://github.com/BillWagner/allReady.git (push)

Instead of my GitHub account, you'll see yours for the 'origin' remotes. 

The next step is to fetch everything from the HTBox copy of the project into your working directory. (This won't change your working files, or your history):

Run 'git fetch HTBox'.

This will pull down the changes into your machine's git repository.

Now comes rebase:

Run "git rebase HTBox/master"

This tells git to rewind your changes, accept everything from HTBox/master (the main branch), then replay your changes.

One of two things will happen:
1. It just works. (:thumbsup:)
2. There are merge conflicts.

In the case of (2), it will tell you which files have conflicts. The conflicts will be marked in your working copy, just like with any source control system. You'll need to hand edit the conflicts.

After that, it's just commit, and push to your fork.

If you have questions, just tag me in a comment here, and I'll help.

**Comment by mgmccarthy** [comment]
@BillWagner, looks like I have a merge conflict:
image

This is what the CampaignController looks like when I open up the solution in VS2015 after I tried the rebase:
image

Looks like the only problem is the using statements at the top?

How do I go about fixing this? Can I make the changes CampaignController, save, and then run "git rebase --continue" or is it more involved than that?

**Comment by BillWagner** [comment]
@mgmccarthy That's correct: make the changes, and continue the rebase.

Then, push.

**Comment by mgmccarthy** [comment]
@BillWagner if I accept these change for the merge, I'm about to lose a lot of work I did on the CampaignController, mediator refactoring and query/handler classes i added. 

If I look at my CampaignController class from my latest commit:
https://github.com/mgmccarthy/allReady/blob/5d83823fc4b527883421b1258dde12244f9464e9/AllReadyApp/Web-App/AllReady/Controllers/CampaignController.cs

the GetUnlockedCampaigns method is missing from the controller. The UnlockedCampaignsQuery and UnlockedCampaignsQueryHandler class files are not even in my current solution.

Either I'm doing this wrong, or rebasing is about trying to recover lost work??

**Comment by YannickMeeus** [comment]
@mgmccarthy Rebasing is basically rewinding your work temporarily, replaying the commits of the upstream branch, then replaying your work on top of that, as if you started work on the current upstream instead of the upstream when you last synced. You shouldn't be losing work but you might have merge conflicts if the upstream commits conflict with your local commits.

**Comment by mgmccarthy** [comment]
@YannickMeeus, so my replaying of commits against the upstream branch is "half done" b/c it's "paused" so I can fix the merge conflict for the rebase to finish? 

After that's done, I'm assuming should be able to see all my work I've committed that I currently think is "lost"?

**Comment by BillWagner** [comment]
@mgmccarthy Let me look. I don't think it should look that way.

**Comment by BillWagner** [comment]
@mgmccarthy I just ran the process locally on your branch.

From where you are now, you'll fix the merge conflict.
Then, add the conflicting file to your commit using 'git add AllReadyApp/Web-App/Allready/Controllers/CampaignController.cs'
Then, continue the rebase:
'git rebase --continue'

I didn't know the code really well, so I still had a conflict I had to merge. (merge, do the git add, then the rebase --continue.)

After that, all your changes were there.

After that, 'git push' and you're done.

Note: you may need to do a 'git push --force' because of the rebase.

**Comment by mgmccarthy** [comment]
@BillWagner, I changed CampaignController which led to a compile error in CampaignControllerTests, so I had to change both files by hand. I "git add"'ed both of them, then tried to rebase --continue, and I get this message:
image

I just edited any conflicts and re-added....

**Comment by BillWagner** [comment]
That looks like the file wasn't added to the commit. Do a 'git status' to see if there are changes that aren't marked for the commit. Then, a 'git add' should fix it.

**Comment by BillWagner** [comment]
Ugh. I think Git is case sensitive. That may be why the add didn't work

**Comment by mgmccarthy** [comment]
lots to look at here for git status:
image

I'm starting to feel like I'm hosed over here. Is there a way to start the rebase over, or at least get my system back into a state where I could try this process again?

**Comment by BillWagner** [comment]
You're really close. git add on those three files and it will work. Can you add me on skype (id is the same as my GitHub handle) a quick call / chat and we're there

**Comment by mgmccarthy** [comment]
@BillWagner, I spent some time with the merges and adding the merged files back to Git, and after  couple attempts, git --rebase continue finally worked. Looking at the files after the rebase, everything looks correct.

However, when finally doing git push, I received this information:
image

1. is the warning about push.default being "unset" something I need to address or be worried about? Do I want to "squelch" the message and maintain the traditional behavior or adopt the new behavior?
2. You can see that my push was rejected. I'm assuming b/c I need to go get the most up to date file from HTBox/allReady, and repeat the git --rebase process?

**Comment by BillWagner** [comment]
@mgmccarthy I'm glad it is all working.
On 1: You can ignore this. It's trying to give you more diagnostics on the 2nd question, and it's not helping. (A bit more detail: Git is assuming that the error is because you're trying to push a branch different than the active branch. You're not. 
On 2: The error is because your local copy now has different history than the remote copy. That's because of the rebase, and is what we want. Git is telling you that the remote has commits that aren't in local and local has commits that aren't in remote. In this case, we know that local is correct, so we can force the push:

git push --force

Obligatory warning: a force push is a dangerous operation. If others had taken your fork and made other changes, they would have to figure out how to get their history in the right place. Because we haven't merged your PR, no one has done that, so it is safe.

Ping me if you have more questions

**Comment by mgmccarthy** [comment]
@BillWagner done

**Comment by BillWagner** [comment]
@mgmccarthy It looks like there is a build error in the unit tests. 

Using Assembly dependency fx/System.Xml.Linq 4.0.0C:\projects\allready\AllReadyApp\Web-App\AllReady.UnitTest\Features\Campaigns\CampaginByCampaignIdQueryHandlerTests.cs(17,13): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'CampaginByCampaignIdQuery' could not be found (are you missing a using directive or an assembly reference?) 
 2972C:\projects\allready\AllReadyApp\Web-App\AllReady.UnitTest\Features\Campaigns\CampaginByCampaignIdQueryHandlerTests.cs(32,26): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'CampaginByCampaignIdQuery' could not be found (are you missing a using directive or an assembly reference?) 

Can you fix that one, and then we're all set.

**Pull request merged**
