### PR TITLE
Basic behavior tests

### PR DESCRIPTION
**Pull request by rmcc13**
Here is an overview of what I have written tests for so far. I have more comments in #787 

- Setting TaskStatus to "Assigned"
- Transitioning TaskStatus from "Assigned" to "Accepted"
- Transitioning TaskStatus from "Assigned" to "Rejected"
- Transitioning TaskStatus from "Accepted" to "Completed"
- Transitioning TaskStatus from "Accepted" to "CanNotComplete"

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@rmcc13, the contribution looks good. A couple suggestions:

- in every test, we're testing the taskSignup.Status being equal t othe TaskStatus.Completed.ToString():
`taskSignup.Status.ShouldBe(TaskStatus.Completed.ToString());`
The code is also setting the incoming message's TaskStatusDescription to the taskSignup.StatusDescription:
`taskSignup.StatusDescription = message.TaskStatusDescription;`
so you could assert that value in each of your unit tests

- if you look at `UpdateMyTasksHandlerAsync` and it's associated unit tests, you can see by using this line in the handler:
`public Func<DateTime> DateTimeUtcNow = () => DateTime.UtcNow;`
you can supply a DateTime in your unit test to the handler and also test `taskSignup.StatusDateTimeUtc` equals the correct DateTime.Utc.

this way, we're explicitly testing all of the properies set on taskSignup that is being returned from `TaskStatusChangeHandlerAsync`.

**Comment by rmcc13** [comment]
OK, thanks for the suggestions. I will look into this over the weekend.

**Comment by rmcc13** [comment]
@mgmccarthy I'm not quite sure if I follow your comment 100%. In your first point, you mentioned all tests were were testing `taskSignup.Status.ShouldBe(TaskStatus.Completed.ToString())`. I'm not sure if you meant we are only testing when tasks are completed, or if you were just using that line of code as an example. I'm assuming the latter. I did however change that test to compare against the command object
`taskSignup.Status.ShouldBe(command.TaskStatus.ToString())`

I am now testing all TaskSignup properties that could be changed in the Handle method. I changed the status test to use the command object, because all other tests are comparing against the command object, and I think the intent is more explicit as we are expecting the status to now be the value we passed to the Handle method.

**Comment by mgmccarthy** [comment]
@rmcc13, looks good. Thanks for all the work. @tonysurma, you can accept this PR when get a chance

**Pull request merged**
