### PR TITLE
Admin area ViewModels refactoring

### PR DESCRIPTION
**Pull request by danielepo**
Addresses issue: "ViewModel folder organization under AllReady\Areas\ (low priority) #890 "
  - Changed name to Models folder in ViewModes
  - Changed classes' postfix Model in ViewModel
  - Moved viewmodels to ViewModels\\[Corresponding Controller Name]
    - e.g. ViewModels\Campaign

### CODE REVIEW

**Comment by tonysurma** [comment]
can you rebase for changes and then I can merge?  Thanks

**Comment by mgmccarthy** [comment]
@danielepo this is going to require a rebase.

@tonysurma I'd try to merge this one very quickly once it's been rebased and there are a lot of naming changes that are happeing to files and to folders

**Comment by tonysurma** [comment]
will do

**Comment by MisterJames** [comment]
@mgmccarthy @tonysurma @danielepo Is there still a need for rebasing here?

**Comment by tonysurma** [comment]
@MisterJames I think this one is good to go now

**Comment by MisterJames** [comment]
Looks like namespace updates and renaming only. Tests pass and we don't have any conflicts, so I'm going ahead with the merge!  :shipit:

**Pull request merged**
