### PR TITLE
Refactored ActivityController to use Mediator

### PR DESCRIPTION
**Pull request by mikesigs**
I moved all/most of the logic from the ActivityController into separate Command+Handler pairs in Features/Activity. There's also some new unit tests.

I also added the Shouldly assertion library and used it in a couple tests.

### CODE REVIEW

**Comment by mikesigs** [comment]
Closes #595

**Comment by mheggeseth** [comment]
@mikesigs FYI, the auto-close syntax ("fixes #[issue]") only happens to work if you put in the PR description. I guess this doesn't really matter because you've already closed #595, but you could reopen it just to try out the feature.

**Comment by MisterJames** [comment]
Good stuff, thanks for the PR @mikesigs!

**Comment by mikesigs** [comment]
No problem. Looking forward to contributing more.

**Pull request merged**
