### PR TITLE
WIP: #919 remove volunteers from event

### PR DESCRIPTION
**Pull request by VishalMadhvani**

### CODE REVIEW

**Comment by tonysurma** [comment]
Hello @VishalMadhvani is this still a work in progress for you?  Also FYI we moved to RTM so you will need to rebase and retest.  Thanks again!

**Comment by VishalMadhvani** [comment]
Thanks @tonysurma!
I was waiting on rtm.. hoping i'll get some time tomorrow to wrap this up.

**Comment by MisterJames** [comment]
@VishalMadhvani I can get this merged in today for you if you are able to resolve the conflicts. Just let me know!

**Comment by VishalMadhvani** [comment]
Sorry all... I've haven't been able to work on allReady for a while and this PR is now very stale.
Closing this PR as its pre ASP.NET Core RTM migration and some of this work has been carried out in recent PR's.

**Pull request closed without merging**
