### PR TITLE
Start of hours screen

### PR DESCRIPTION
**Pull request by cjmartin6162**
layout done. still need to have logic for saving back to database done.  need to be able to associate to event still.  

#1189

### CODE REVIEW

**Comment by MisterJames** [comment]
@cjmartin6162 can you rebase this for us? It should fix the build error when you do a new commit.

**Comment by cjmartin6162** [comment]
@MisterJames done

**Comment by tonysurma** [comment]
Thanks @cjmartin6162 Is this good to merge and then we can add in the additional logic bits you talked about later as another issue?

**Comment by tonysurma** [comment]
@cjmartin6162 @MisterJames checking in again?  Thanks

**Comment by digitaldrummerj** [comment]
@tonysurma This one is good to merge.  I worked with @cjmartin6162  on this as part of the AZ Give Camp hackathon last month.

**Pull request merged**
