### PR TITLE
Adding ability to edit itinerary

### LINKED ISSUE #1331: Add page to edit an Itinerary
This page or popup should allow an admin to update the date and title of an itinerary.

### PR DESCRIPTION
**Pull request by stevejgordon**
Fixes #1331 

This is an initial quick pass to enable editing an itinerary. The main purpose is to allow a start/end address to be set for an itinerary to the be used in my work for issue #1102 

I'll continue with that issue once this is merged.

Note: I've not included unit tests for the edit itinerary handler yet. I'll open a follow up issue for that.
The validation also needs tweaking to validate the addresses as well. Again, I'll follow that up in a new issue.

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@stevejgordon, are we allowing the editing of an Itinerary's date?

**Comment by stevejgordon** [comment]
@mgmccarthy Currently, yes. This was mostly put in to manage the addresses though.

The editing of the date may have some impact on the notifications I guess. I can remove it from this PR. It does feel reasonable that someone may need to adjust an itinerary date but we'd need to decide on handling the change.

Also, there's not specific validation on this yet. It's a bit quick and dirty to enable the work on the route optimisation.

**Comment by mgmccarthy** [comment]
@stevegordon. Don't remove it until I have a chance to look at the scheduling/hangfire stuff. There might be a way to handle it in the job code.

**Comment by mgmccarthy** [comment]
@stevejgordon, to me, should we have the ability to edit an Itinerary's date is more of a business question than a technical concern, but by allowing the editing of an Itinerary's date at any point in the lifetime of the Itinerary will force us to write more code which will create complexity.

From a technical point of view, I have two concerns that add complication to the system:

1. Hangfire jobs "in-flight": since we schedule Hangfire jobs based on the Itinerary's date, changing the date could potentially lead to sms messages that are either not sent, or sent on the wrong date. 
2. Itineraries that have had requestor's confirm their request means they confirmed their request based on the date of the Itinerary that the Request was added to. If we were to change the Itinerary date after a requestor(s) confirmed their request with us, now we need to go through a look-up process, and re-send more confirmation messages to requestors notifying them that the date of the Itinerary has changed and they need to confirm the new date with us.

Because we'd have to add code to address these two issues above, which can create more complexity, here is a list of what we could do in order of easiest to hardest.

1. once an Itinerary has been changed, do not allow it's date to be edited
2. once an Itinerary has one Request assigned to it (regardless of the source of the Request), do not allow the date to be edited
3. allow the date to be edited at any point once an Itinerary has been created (I don't think we should choose this option for the reasons I outlined above).

@tonysurma @MisterJames @dpaquette what are your thoughts?

**Comment by tonysurma** [comment]
Let's remove editing date to make simplicity a winner.  We can open an issue on feature backlog for date editing and see if it ever gets prioritized and then we're can deal with the complexity noted above.

When you remove that @stevejgordon we can merge this

**Comment by mgmccarthy** [comment]
@tonysurma, had a quick chat with @stevejgordon this morning about this and it sounds like we're all on the same page. Thanks.

**Comment by mgmccarthy** [comment]
@stevejgordon, let me know if I can help in any way

**Comment by stevejgordon** [comment]
@tonysurma All done and ready to go

**Pull request merged**
