### PR TITLE
Logging hours togglable

### PR DESCRIPTION
**Pull request by enderdickerson**
Enhances #1189

### CODE REVIEW

**Comment by tonysurma** [comment]
@digitaldrummerj can you give this a quick review?  Thanks

Thanks @enderdickerson for the contribution!

**Comment by digitaldrummerj** [comment]
@tonysurma yes I can take a look at it.

**Comment by tonysurma** [comment]
thanks @digitaldrummerj after your review I will merge

**Comment by tonysurma** [comment]
@digitaldrummerj any update on review?

**Pull request merged**
