### PR TITLE
Campaign Information / Resources #1783

### PR DESCRIPTION
**Pull request by HamidMosalla**
Fixes: #1783
The ability to add, remove, edit resource for a campaign is implemented, currently there is no unit test for the added features, I add them once we made sure the changes are in line with the requirements.

### CODE REVIEW

**Comment by stevejgordon** [comment]
@HamidMosalla Sorry for the delay. I'll try to get eyes on this over the next few days around work.

**Comment by stevejgordon** [comment]
@HamidMosalla Finally got this pulled down to test it and it's looking like a great start to me. It's what I had in mind for the v1 requirement.

The breadcrumbs at the top might need a little fixing up but it's already looking very close to something we can merge in. If you're able to finish off with a few tests and fixup the breadcrumb I'll do a proper look over the code before it get's merged.

**Comment by HamidMosalla** [comment]
@stevejgordon Thanks for the review, in the main page of the issue you've asked:
> Can you please confirm if these should be visible on the public pages (i.e. including non logged in, general public users) or should this only be shown on the page once someone is a volunteer for one of the tasks under a campaign?

 and @schuback said:

> These should be behind the login process as a signed up volunteer on a campaign

Should I add a page for volunteers or the current details page will do? or maybe I should show and hide the buttons based on the role?

**Comment by tonysurma** [comment]
Let's show this without and security filtering and bring the code in now and then can you log a septate issue noting and linking to this PR and the issue that they need the security filtering? This way we get your code and PR in author that complication.  Thanks

**Comment by HamidMosalla** [comment]
@tonysurma If this feature is needed faster, maybe I could finish the breadcrumb problem so we can merge this and then open an issue for unit tests and security? Because I might not be able to work on it for the next three or four days, let me know if it's OK with you.

**Comment by tonysurma** [comment]
Thanks @HamidMosalla I think it's less about needing it faster and more about breaking it into chunks and sperating out the security part that feels like it needs a bit more clarity.  Working on it after three or four days or in a week or two is plenty soon enough and thank you

**Comment by tonysurma** [comment]
@HamidMosalla can you rebase off of current to pick a build fix and then once we see it build we can merge it in.  Thanks!

**Comment by HamidMosalla** [comment]
@tonysurma I'm not sure I understand what you're saying, do you mean I should fetch the latest changes, resolve issues if any, and rebase my commits on top of them?

**Comment by tonysurma** [comment]
thanks @HamidMosalla .  Yes we merged into master a fix to make this all build.  If you can rebase off of that (as you would before submitting a PR) that would be great.

Probably info you already have/know but here are a couple of links we point folks to related to this:
https://www.stevejgordon.co.uk/contributing-to-allready
http://www.davepaquette.com/archive/2016/01/24/Submitting-Your-First-Pull-request.aspx

**Comment by HamidMosalla** [comment]
@tonysurma There some weird things going on, when I've tried to rebase I've encountered with couple of conflicts, when I resolve them and continue, I get some more conflicts that doesn't make sense:

```
Falling back to patching base and 3-way merge...
CONFLICT (rename/add): Rename AllReadyApp/Web-App/AllReady/Areas/Admin/ViewModels/Resource/ResourceCreateViewModel.cs->AllReadyApp/Web-App/AllReady/Areas/Admin/ViewModels/Resource/ResourceEditViewModel.cs in add
 action method and handler for creating resource. AllReadyApp/Web-App/AllReady/Areas/Admin/ViewModels/Resource/ResourceEditViewModel.cs added in HEAD
Adding as AllReadyApp/Web-App/AllReady/Areas/Admin/ViewModels/Resource/ResourceEditViewModel.cs~HEAD instead


CONFLICT (rename/add): Rename AllReadyApp/Web-App/AllReady/Areas/Admin/Views/Resource/Create.cshtml->AllReadyApp/Web-App/AllReady/Areas/Admin/Views/Resource/Edit.cshtml in add action method and handler for creat
ing resource. AllReadyApp/Web-App/AllReady/Areas/Admin/Views/Resource/Edit.cshtml added in HEAD
Adding as AllReadyApp/Web-App/AllReady/Areas/Admin/Views/Resource/Edit.cshtml~HEAD instead
Auto-merging AllReadyApp/Web-App/AllReady/Areas/Admin/Views/Resource/Edit.cshtml
Auto-merging AllReadyApp/Web-App/AllReady/Areas/Admin/ViewModels/Resource/ResourceEditViewModel.cs
Auto-merging AllReadyApp/Web-App/AllReady/Areas/Admin/Controllers/ResourceAdminController.cs

CONFLICT (content): Merge conflict in AllReadyApp/Web-App/AllReady/Areas/Admin/Controllers/ResourceAdminController.cs
error: Failed to merge in the changes.
```

For example I renamed the `EditResourceCommandHandler` to `CreateOrEditResourceCommandHandler` but the file doesn't exist in my solution, and also the lock icons are gone from my files in VS solution, also I usually use Visual Studio to resolve conflicts, but there is no option to resolve conflicts for aforementioned files as well as files mentioned in the git rebase message, any idea?

**Comment by HamidMosalla** [comment]
@tonysurma After certain amount of hair pulling I've rebased my commits on top of latest changes, I hope you can merge without problems.

**Comment by HamidMosalla** [comment]
@tonysurma I hope I haven't offended you by my last comment, my problems with git results form my lack of know-how in that area, I didn't mean to imply otherwise. One has to know the git deep or else if something you didn't see before comes up, you're in for trouble. People who English is their second language can sometimes say things they don't mean, In this case I was trying to be humorous, I just wanted to make sure there is no misunderstanding.

**Comment by tonysurma** [comment]
Oh goodness no @HamidMosalla I hope I haven't done anything to imply that I was in any way offended.

I hadn't replied as it looked like you resolved it and I was able to merge it in so it was all good.

I fully took it as humorous and frankly continue to be frustrated by git from time to time despite having worked with it for many years and being someone who teaches others how to use it.  Git is seemingly by design powerful, obtuse and annoying 😄 

It's all good and we couldn't be happier you are volunteering your time to contribute to HTBox.

Thanks!

**Comment by HamidMosalla** [comment]
@tonysurma Good to know, you didn't imply it, I just feel sometimes what I utter in words can be interpreted differently and is not what I really think and trying to covey, it happens a lot, with ESL speakers, it doesn't hurt to be as clear as possible.

**Comment by tonysurma** [comment]
Excellent, glad to hear it.  While I fully appreciate how that can happen with ESL speakers often, I find it also happens in written communications (email, IM, txt, etc.) as it is not always easy to read the 'tone' of what was written without hearing voice and body language.  Its always good to make sure no 'unintended side effects' happened - just like in code 😄

**Pull request merged**
