### PR TITLE
Unit tests issue870

### PR DESCRIPTION
**Pull request by benjaminettori**
#870

### CODE REVIEW

**Comment by benjaminettori** [comment]
@mgmccarthy : should be working now.

**Comment by mgmccarthy** [comment]
@benjaminettori on vaca this week. Another product owner might be able to get to it. If not, I'll take a look next week.

**Comment by BillWagner** [comment]
Looks good.  Merging now.

**Comment by mgmccarthy** [comment]
Thanks @BillWagner

**Pull request merged**
