### PR TITLE
Accept event and campaign manager invites

### LINKED ISSUE #1891: Acceptance of ManagementInvite
Breakout from #1804

Upon clicking the accept invite link, a user should to be taken to the accept invite page. 

@schuback - Should clicking the link immediately accept the invite for a logged in user (and take them to a invite accepted page? Or should we redisplay the details and require an explicit accept button click to take place?

We should require login to access this page. If the user does not have an account, they will need to create one first.

We might need to consider the flow to direct the user to the accept invite page if they are newly created after their first full login? This would enable a slightly nicer user journey. We can review that and enhance as necessary.

Upon accepting the invite, we should update the invite table and set the user in the appropriate management table - i.e CampaignManager

### PR DESCRIPTION
**Pull request by mk0sojo**
Added accept and decline functionality to event and campaign manager invites

Closes #1891

### CODE REVIEW

**Comment by mk0sojo** [comment]
I get the error message 
"nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
The source specified has already been added to the list of available package sources. Please provide a unique source.
Command exited with code 1"

Do anyone know why this is appearing?

**Comment by VishalMadhvani** [comment]
yeah looks like appveyor updated the build images.
#2168 should fix the build.

**Comment by mk0sojo** [comment]
Thanks @VishalMadhvani, That should fix it I think.
Does anyone know how to trigger a new build?
Looking at appveyor documentation, it looks like it has to be triggered from the dashboard on their website?

**Comment by VishalMadhvani** [comment]
Try pushing an update to your branch with a dummy commit, or potentially closing and reopening the pull request.

**Comment by mk0sojo** [comment]
that fixed it. thanks.

**Pull request merged**
