### PR TITLE
Displaying date times in correct time zone

### PR DESCRIPTION
**Pull request by dpaquette**
- Campaigns and Users now have time zone associated with them
- Time Zone name is displayed next to campaign/activity/task times
- Still need to figure out how to deal with timezone conversions for times in knockout bindings
- Need to add tests
- Would like to improve look of date/time display for campaigns/activities/tasks

### CODE REVIEW

**Comment by joelhulen** [comment]
Have you considered using the moment.js library for javascript-based timezone conversions for our knockout bindings? I imagine we could create a custom ko binding that references the lib, or at least do the conversion via convention. Here's more info on moment.js: http://momentjs.com/timezone/

**Comment by dpaquette** [comment]
@joelhulen yeah we are using momentjs already. I just haven't looked at how to ensure we are doing the conversions consistently. Javascript's concept of a timezone is different than .NET's concept of a timezone. Basically I thought I was done and then realized there are a few places were the date are being handled / formatted on the client side.

**Comment by dpaquette** [comment]
Dates that are formatted in javascript are not correctly being displayed in the timezone of the campaign. 

This is ready for review. I'm going to add a few more unit tests but would be great if someone could review while I work on that.

**Comment by dpaquette** [comment]
Ready for review.

One thing to note for the folks testing is that times might be a little off for any existing data. Opening and saving the Campaign / Activity / Task will fix that.

**Comment by BillWagner** [comment]
I reviewed all the code as of commit 5c9affc6715cccf1d214eef6e29072da9112db7d and I'm good.

@dpaquette Are there more tests coming? I'll merge if not.

**Comment by dpaquette** [comment]
No that's it

**Pull request merged**
