### PR TITLE
Preview a campaign before publishing/saving #1582

### PR DESCRIPTION
**Pull request by HamidMosalla**
Closes: #1582

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@HamidMosalla, I'll try to get to a code reveiew of this today/tonight.

**Comment by HamidMosalla** [comment]
@mgmccarthy Thank you, I should mention that the preview tab is handled by client side.

@tonysurma 
> it doesn't have to be 'long lived' aka stored in system.

I completely handled it on the client side, we didn't need the server for what needed to be done (provided I understood the requirement correctly), but it also could have been handled by server side using AJAX request and partial views, the preview tab will look like something like this:

untitled

Also we don't see any image if it's in create mode.

**Comment by mgmccarthy** [comment]
> I should mention that the preview tab is handled by client side

:fearful:

@dpaquette @MisterJames could you handle this one?

**Comment by HamidMosalla** [comment]
@mgmccarthy I didn't like the previous implementation at all, it was messy, so I changed it, in the new implementation I use a partial view for preview tab and load it via AJAX request, now there is only 6 line of trivial JavaScript code, also I noticed a blunder regarding deleting campaign and event's image while I was fiddling with campaign preview tab, I corrected them too.

**Comment by tonysurma** [comment]
thanks @HamidMosalla 

@dpaquette @MisterJames can you review this?  I tried to add you as reviewers but appears that new functionality isn't working it.  Thanks

**Comment by tonysurma** [comment]
@HamidMosalla can you look into rebasing after we have merged a few other PRs, @dpaquette @MisterJames if you can take a peek for review that would be great

**Comment by HamidMosalla** [comment]
@tonysurma I'll do it after the code review, just in case there was any requested changes.

**Comment by tonysurma** [comment]
Great idea, thanks again

**Comment by dpaquette** [comment]
This looks good to me. While it could be done all client-side, doing the preview with an ajax request and a partial view keeps it simple and will likely be easier for folks to understand.

**Comment by tonysurma** [comment]
@hamidmosalla after a rebase we will merge this on.  Thanks

**Comment by HamidMosalla** [comment]
@tonysurma @MisterJames I messed up my local repository, but I managed to do a rebase and resolve conflicts with fingers crossed, please take another look at it before merge, sorry about that, I obviously don't know that I'm doing when it comes to git.

**Comment by tonysurma** [comment]
Looks good to me.  FYI @stevejgordon and @dpaquette amongst others are always happy to help on git and have blog posts that may help as well.

**Pull request merged**
