### PR TITLE
663 campaign controller

### LINKED ISSUE #663: finish unit tests for AllReady.Areas.Admin.Controllers.CampaignController
@tonysurma please label with "jump-in". Part of Issue #620

some tests exist, but the rest are stubbed out in:
AllReady.UnitTest.Areas.Admin.Controllers.CampaignAdminControllerTests

### PR DESCRIPTION
**Pull request by sanilpaul**
fixes #663

### CODE REVIEW

**Comment by tonysurma** [comment]
@mgmccarthy have you had a chance to review?  Thanks @sanilpaul for your contributions!

**Comment by mgmccarthy** [comment]
@tonysurma, not yet. I should get a chance to review it by late weekend or early next week.

**Comment by sanilpaul** [comment]
@tonysurma @mgmccarthy Any idea why my pull request shows all previous commits not related to this issue?

**Comment by mgmccarthy** [comment]
@sanilpaul, did you create your new branch from master after fetching then merging?

**Comment by sanilpaul** [comment]
@mgmccarthy Yes. Not sure whether I did something wrong when I set it up. Once the existing PRs are merged, I will start over.

**Comment by tonysurma** [comment]
@sanilpaul what PRs do you need merged first then?

**Comment by sanilpaul** [comment]
@tonysurma  you could merge both PR's.  if @mgmccarthy is okay with that. For the next PR, I will work with Mike to double check. There wouldn't be any impact. 

These are the commits that are relevent to this PR. 

Add initial test			8f1e11e
add test for delete image			df1cd40
add test for no previous campaign image			124f4af
add missing test to verify error message			3149ca6
test route values			8cf7ef5

**Comment by mgmccarthy** [comment]
@tonysurma :shipit:

**Pull request merged**
