### PR TITLE
#661 More tests for AccountController

### PR DESCRIPTION
**Pull request by arst**

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames @BillWagner I'm done code review. Please merge.

@arst thanks for tackling some of the hardest unit tests in the system. Nice work.

**Comment by MisterJames** [comment]
@arst looks like we're going to need a rebase here when you get a chance.

**Comment by mgmccarthy** [comment]
Sorry about that @MisterJames, I pulled each of their branches locally, and when I looked at what they added to the test file, there was no overlap. Something maybe I missed? :disappointed: 

@arst, let me know if you need help on the reabase.

**Comment by arst** [comment]
@MisterJames Rebased.

**Comment by MisterJames** [comment]
@mgmccarthy  Nah...I call it a git miss. Just happens when there's too many changes on the same file, I think git just gives up :smile:

**Pull request merged**
