### PR TITLE
Resolves Issue #862

### PR DESCRIPTION
**Pull request by bsstahl**
Resolves Issue #862

### CODE REVIEW

**Comment by tonysurma** [comment]
@mgmccarthy quick review before we merge?

**Comment by mgmccarthy** [comment]
@tonysurma, my development machine is currently smoked... working on it now. The best I can do is eyeball this PR (I usually pull down and use my IDE)...

**Comment by mgmccarthy** [comment]
@tonysurma, my dev machine is toast. I have to wait until next Tuesday to get it fixed by our comapany's service desk, so I will be unable to do any code reviews until then

**Comment by mgmccarthy** [comment]
@tonysurma, my machine is back. I'm going to try to get a review for this in the next day or two

**Comment by mgmccarthy** [comment]
@tonysurma :shipit:

**Pull request merged**
