### PR TITLE
Reorder requests

### LINKED ISSUE #876: Ability to re-order requests in an itinerary
We need to be able to do basic request ordering on the itinerary management page.

The schema includes an orderindex column which we'll use to do this.

### PR DESCRIPTION
**Pull request by stevejgordon**
Closes #876 

Very basic re-ordering functionality added to the requests under an itinerary.

@tonysurma This was accidently based off of a branch from an earlier PR so I'll need to rebase it from master once all others are merged. Just let me know and I'll get that done when you're ready.

### CODE REVIEW

**Comment by tonysurma** [comment]
doesn't look it needs a rebase @stevejgordon Let me know if I should merge

**Comment by tonysurma** [comment]
now it needs a rebase :)

**Comment by stevejgordon** [comment]
I've rebased locally but it's not quite working so I'll need to debug it later and validate the behaviour. Something in the merge has broken it!

**Comment by stevejgordon** [comment]
Please don't accept until I've squashed those bugs.

**Comment by stevejgordon** [comment]
image

I think this is okay to go now. Checked it out at the start of my lunch break and can't replicate the issue I saw first thing. I've tweaked the UI though so it's a bit (not much) more pleasing!

**Pull request merged**
