### PR TITLE
pull email and name from Twitter external login provider

### LINKED ISSUE #977: pull email and name from Twitter external login provider
@tonysurma please assign to me.

I'm currently working on this.

### PR DESCRIPTION
**Pull request by mgmccarthy**
Fixes #977

the first couple commits will look familiar as they're from PR #969. 

The changes for the #977 functionality being with ['add Google External Auth' afcb85e](https://github.com/HTBox/allReady/commit/afcb85e7a78f31fb8d7965b7eda2eb5fd0227c01). In addition to writing code to get the email and name from Twitter, I also decomposed and encapsulated the code for how the different external login providers fetch the information and abstracted that away from AccountController:

- created `ExternalUserInformationProviders` per external login provider. These control how First Name, Last Name and Email are fetched.
- these providers are instantiated at runtime by the `ExternalUserInformationProviderFactory` which implements `IExternalUserInformationProviderFactory` and is injected into AccountController and registered in the container.
- updated/stubbed out AccountControllerTests to reflect the new provider factory code changes.

### CODE REVIEW

**Comment by mgmccarthy** [comment]
@MisterJames, just rebased. Should be good to merge

**Comment by tonysurma** [comment]
I haven't been able to review, @MisterJames have you?  After that and rebase we can get this in.  Thanks @mgmccarthy for your patience

**Comment by tonysurma** [comment]
I was going to merge but not sure what to do with the commits that were from the past PR.  @BillWagner or @MisterJames thoughts?  Will it cause any issues if they are re-merged in?

**Comment by mgmccarthy** [comment]
@tonysurma, the commits from the past PR we're already merged, so it should not cause any issues.

**Comment by tonysurma** [comment]
I would think that too but it was squashed when it was merged so those individual commits 'don't exist' in the main repo, so not sure what bringing them in again will do.  I will test it on my local machine later today unless they have some bright ideas.  Thanks again!

**Comment by BillWagner** [comment]
@tonysurma Merging will be safe. Those commits don't exist in the main repo, but the changes do. Therefore, the diffs generated from them will be no-ops.

**Pull request merged**
