### PR TITLE
Fixes default dates for new campaign; closes #336

### LINKED ISSUE #336: Default campaign start/end dates on Create page are 1/1/0001

### PR DESCRIPTION
**Pull request by ksk100**
Closes #336

### CODE REVIEW

**Comment by ksk100** [comment]
closes #336

**Comment by dpaquette** [comment]
Looks good. :shipit:

**Comment by mheggeseth** [comment]
FYI, "Closes #336" has to be in the PR description in order for it to work. Just having it in comments doesn't automatically close the issue.

**Comment by ksk100** [comment]
Ah okay; no problem.

**Pull request merged**
