### PR TITLE
#426 tenants become organizations dbv2

### LINKED ISSUE #426: Death to Tenants! Long live Organizations! (Database Edition)
After the simpler renaming changes listed in #423, completing the renaming of "Tenant" to "Organization" includes renaming database entities as well. Though this will be an involved change from a testing coordination perspective, the pain of the change increases significantly the longer we put it off so let's rip this band-aid off as soon as we can.

This issue is intended to start the conversation about when and how to accomplish this change from a testing/deployment perspective so this is where folks like @tonysurma, @OhMcGoo, and @BillWagner come in.

### PR DESCRIPTION
**Pull request by stevejgordon**
New PR to hopefully close #426 

@mheggeseth Perhaps you can review and hopefully merge in before any further changes to avoid conflicts?

### CODE REVIEW

**Comment by mheggeseth** [comment]
Technical is a :shipit: pending deployment go-ahead from @tonysurma. *Note that this will require every allReady contributor and deployment to delete and re-create their DB.*

**Comment by BillWagner** [comment]
@stevejgordon Can you update to fix the merge conflicts? @tonysurma can you give your review if this is ready to merge?

**Comment by stevejgordon** [comment]
@BillWagner Sure, I'll give it a try ASAP. Hoping whatever went wrong in my previous PR when I rebased doesn't happen again. Any tips before I try it? Do I simply fetch the master from HTBox/Allready into my local repo, then on my branch rebase off my updated local master?

**Comment by BillWagner** [comment]
@stevejgordon I usually follow the instructions here: https://robots.thoughtbot.com/keeping-a-github-fork-updated
That works for me. I'm online for the next few hours, if you run into issues.

**Comment by stevejgordon** [comment]
@BillWagner I think I've got it to work. It wasn't 100% straightforward but I was following some steps from a StackOverflow post. Basically I did the following...

git checkout master
git fetch HTBox (this is the name of my remote to the main repo)
git merge HTBox/master
git checkout #426-TenantsBecomeOrganizationsDbv2
git rebase master

Up to this point everything was as described. The only issue I had was when I tried to git push origin #426-TenantsBecomeOrganizationsDbv2

I got an error:
 ! [rejected]        #426-TenantsBecomeOrganizationsDbv2 -> #426-TenantsBecomeOrganizationsDbv2 (non-fast-forward)
error: failed to push some refs to 'https://github.com/stevejgordon/allReady.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

In the end I took a gamble and did my push with a --force to update the GitHub repo.

**Pull request merged**
