### PR TITLE
Issue860

### LINKED ISSUE #860: write unit tests for NotifyAdminForSignup
@tonysurma please label with "jump-in". Part of Issue #620

### PR DESCRIPTION
**Pull request by bsstahl**
Fixes #860

### CODE REVIEW

**Comment by tonysurma** [comment]
@mgmccarthy quick review and I will merge.  Thanks again @bsstahl for the contributions during the code camp!

**Comment by mgmccarthy** [comment]
@tonysurma, my dev machine is toast. I have to wait until next Tuesday to get it fixed by our comapany's service desk, so I will be unable to do any code reviews until then

**Comment by mgmccarthy** [comment]
@tonysurma, my machine is back. I'm going to try to get a review for this in the next day or two

**Comment by mgmccarthy** [comment]
@tonysurma :shipit:

**Pull request merged**
