### PR TITLE
#1818 Hide request filter when no requests

### LINKED ISSUE #1818: Itinerary Details Page - Hide request filter when no requests
It would be nice to hide the requests filter on the Itinerary Details page when there are no requests assigned.

e.g. http://localhost:48408/Admin/Itinerary/Details/3

### PR DESCRIPTION
**Pull request by arst**
Closes #1818.
Checks for  requests existence before render the filters.

### CODE REVIEW

**Comment by arst** [comment]
AppVeyour build failed.

**Comment by stevejgordon** [comment]
Hi @arst - Feel free to keep the PR open, but marked as WIP while you're working on it if you want any interim reviews / help with anything.

**Comment by arst** [comment]
Thanks @stevejgordon - actually, I don't think that my changes for this one could possibly affect the build(caues it is a small changes in a view file), so I'm still trying to figure out what is causing it to fail.

**Comment by tonysurma** [comment]
I was going to re-run the build to see the issue but it won't work as I can't re-open the PR.  If you reopen or recreate I will happily help determine the issue.  Thanks!

**Comment by tonysurma** [comment]
looking at changes, looks like somehow changes to the appveyor.yaml file came through and I would guess those are the issue.  thanks again

**Comment by arst** [comment]
@tonysurma Thanks for your help! I dropped this one and created a pull request #1854 to make sure that it doesn't affect the build, but seems that build is still fails :(

**Pull request closed without merging**
