### PR TITLE
Allow a Campaign Manager User to modify Campaign Goals

### LINKED ISSUE #2146: Campaign Manager Cannot add goals to a campaign STARWEST FUNCTIONALITY
Campaign manager cannot add goals to a campaign.

Attempting to add a goal to a campaign by a campaign manager generates an error message:

Access denied due to insufficient permissions.

Rob

### PR DESCRIPTION
**Pull request by VishalMadhvani**
Fixed #2146

### CODE REVIEW

**Comment by MisterJames** [comment]
@VishalMadhvani thanks for this fix, looks good save the NREs in the tests. Can you have a look into those?

**Comment by stevejgordon** [comment]
@VishalMadhvani - Just checking if to see if you think you'll have time to fix up the unit tests on this one?

**Comment by GProulx** [comment]
If @VishalMadhvani doesn't have time, I can take care of that later this week if you want.

**Comment by VishalMadhvani** [comment]
No sorry i haven't had time to look at the tests at all... feel free to grab it @GProulx

**Comment by VishalMadhvani** [comment]
Finally got round to making these tests pass.

**Pull request merged**
