### PR TITLE
Guard against null addressee

### PR DESCRIPTION
**Pull request by SeanFeldman**
Also use full async

### CODE REVIEW

**Comment by SeanFeldman** [comment]
The build is failing but can't see what's the reason. Please help.

**Comment by BillWagner** [comment]
*sigh* another time out. I kicked it off again.

**Comment by SeanFeldman** [comment]
@BillWagner AppVeyor says "Build execution time has reached the maximum allowed time for your plan (60 minutes)."

**Comment by tonysurma** [comment]
@SeanFeldman please rebase off of master as we now have a fix for the build/test issues!

**Comment by SeanFeldman** [comment]
@tonysurma rebased

**Pull request merged**
